# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

### Observations and Insights

1.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
data_file = "../output_data/output.csv" 

weather_data = pd.read_csv(data_file)
weather_data.drop(columns=["Unnamed: 0"], inplace=True)
weather_data.head()

,City,Country,Date,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed
0,Faya,SA,1612823995,18.3851,42.4509,50.00,81,40,8.05
1,Aljezur,PT,1612823734,37.3191,-8.8033,54.00,100,53,3.00
2,Kapaa,US,1612823995,22.0752,-159.3190,75.99,60,75,14.97
3,Cape Town,ZA,1612823936,-33.9258,18.4232,70.00,83,20,20.71
4,Castro,BR,1612823996,-24.7911,-50.0119,64.90,79,43,8.75

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [ ]:
locations = weather_data[["Latitude", "Longitude"]]

humidity  = weather_data["Humidity"].astype(float)

fig = gmaps.figure()

heatmap_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, point_radius=5)

fig.add_layer(heatmap_layer)
fig

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
vacation_spots = weather_data.loc[weather_data['Max Temperature'] < 85]
vacation_spots = vacation_spots[vacation_spots['Max Temperature'] > 70]
vacation_spots.head()

,City,Country,Date,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed
2,Kapaa,US,1612823995,22.0752,-159.3190,75.99,60,75,14.97
6,Hithadhoo,MV,1612823996,-0.6000,73.0833,82.42,78,88,10.58
8,Ancud,CL,1612823996,-41.8697,-73.8203,77.00,47,0,8.05
14,Mahibadhoo,MV,1612823998,3.7833,72.9667,81.84,72,10,18.39
18,Vaini,TO,1612823998,-21.2000,-175.2000,80.60,94,90,12.66

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
def call_places(latitude, longitude, radius, searchType, keyword, key):
    call_string = f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={latitude},{longitude}&radius={radius}&type={searchType}&keyword={keyword}&key={key}"
    return call_string

In [7]:
hotel_df = pd.DataFrame(vacation_spots, columns=["City", "Country", "Latitude", "Longitude"])

hotel_df["Hotel Name"] = ""
hotel_df

           City Country  Latitude  Longitude Hotel Name
2         Kapaa      US   22.0752  -159.3190
6     Hithadhoo      MV   -0.6000    73.0833
8         Ancud      CL  -41.8697   -73.8203
14   Mahibadhoo      MV    3.7833    72.9667
18        Vaini      TO  -21.2000  -175.2000
..          ...     ...       ...        ...        ...
556        Tafo      GH    6.7345    -1.6127
557      Vanimo      PG   -2.6741   141.3028
558      Banjar      ID   -8.1900   114.9675
559     Hualmay      PE  -11.0964   -77.6139
562  Morant Bay      JM   17.8815   -76.4093

[189 rows x 5 columns]

In [ ]:
hotel_name = []
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Latitude"]
    lng = row["Longitude"]
    
    url = call_places(lat,lng,5000,'hotel','hotel',g_key)
    
    # make request and print url
    name_address = requests.get(url)
    
    # convert to json
    name_address = name_address.json()
    print(json.dumps(name_address, indent=4, sort_keys=True))
    try:

        hotel_name.append(name_address['results'][0]['name'])
    except IndexError:
        hotel_name.append(np.nan)

{
    "html_attributions": [],
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0567556,
                    "lng": -159.3225167
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.05819822989272,
                        "lng": -159.3212921201073
                    },
                    "southwest": {
                        "lat": 22.05549857010728,
                        "lng": -159.3239917798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Sheraton Kauai Resort at Coconut Beach",
            "photos": [
                {
                    "height": 4911,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/102245644131612923346\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJ6wEAfALC6rei4EcgPGz4olSVysJG1rwumm_ov-w7ZJLV154czRvk_ic43MATuAlgXejVs1VYRQmITAjB7QkzHMxrU9yXSpVeLdd-Z1A-3NSjDuyz3tmXZftdZFdWS_6FMRQyT_ZSbPUZfaNKNPBsAxPMH4mXZ0-B496cDWaIw7F2u",
                    "width": 7358
                }
            ],
            "place_id": "ChIJ9w86akXgBnwRigZV5hBBVJc",
            "plus_code": {
                "compound_code": "3M4G+PX Kapa\u02bba, Hawaii",
                "global_code": "73J23M4G+PX"
            },
            "rating": 4.1,
            "reference": "ChIJ9w86akXgBnwRigZV5hBBVJc",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 1482,
            "vicinity": "650 Aleka Loop, Kapa\u02bba"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0591196,
                    "lng": -159.3202098
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.06052907989272,
                        "lng": -159.3189125201073
                    },
                    "southwest": {
                        "lat": 22.05782942010728,
                        "lng": -159.3216121798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "The ISO",
            "photos": [
                {
                    "height": 3024,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/113960313408989243185\">\u306b\u3083\u3093\u3053\u5148\u751f</a>"
                    ],
                    "photo_reference": "ATtYBwJnQma_GvLFEVrlMMBOs-DoKAE2IAK_J_dkuJBRYRlnHus7XqO7ukjUVmwDy4BsMPCUR3zBGO47OJP7l98Mjj-A6sx-SC0YaBy0h3_9Mb0jRwBfBys8sXC4rYc1FU6QbzXBgk7_9cRhzXKGQmuvXH3zM3TGf0RllBK2ebVQhyNq6-gx",
                    "width": 4032
                }
            ],
            "place_id": "ChIJP7HqslvgBnwRGMjdFcAq3ac",
            "plus_code": {
                "compound_code": "3M5H+JW Kapa\u02bba, Hawaii",
                "global_code": "73J23M5H+JW"
            },
            "rating": 4,
            "reference": "ChIJP7HqslvgBnwRGMjdFcAq3ac",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 396,
            "vicinity": "4-796 Kuhio Hwy, Kapa\u02bba"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0422873,
                    "lng": -159.3370131
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.04377892989272,
                        "lng": -159.3358772701073
                    },
                    "southwest": {
                        "lat": 22.04107927010728,
                        "lng": -159.3385769298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hilton Garden Inn Kauai Wailua Bay",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2624,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/104306026725180198516\">Hilton Garden Inn Kauai Wailua Bay</a>"
                    ],
                    "photo_reference": "ATtYBwLtip_v4ooAyniS1ASxTkDuNNUJQMyKtQX_S_ldWKrDaVwFhvElcSGQ6Q13Q7j-FcImDVAojRsgvY_FXOFeC5EFuaoh6Wr54Db4i72VD65Sf7LPifAFj1jPJbaj2R_0yQQWPHKRIjLfC5UYTHob0PqYcpbSAyVQq0LWnal4s0ICTr2K",
                    "width": 3936
                }
            ],
            "place_id": "ChIJT-qCmczhBnwR5NfROLBuGvg",
            "plus_code": {
                "compound_code": "2MR7+W5 Kapa\u02bba, Hawaii",
                "global_code": "73J22MR7+W5"
            },
            "rating": 4.2,
            "reference": "ChIJT-qCmczhBnwR5NfROLBuGvg",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 1005,
            "vicinity": "3-5920 Kuhio Hwy, Kapa\u02bba"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0529894,
                    "lng": -159.3284284
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.05445072989273,
                        "lng": -159.3270617201073
                    },
                    "southwest": {
                        "lat": 22.05175107010728,
                        "lng": -159.3297613798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Aston Islander on the Beach",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 1960,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/107610353743252387030\">Robert DeMeyer</a>"
                    ],
                    "photo_reference": "ATtYBwJaFoQp1GrShuQYylCzGB1oIYNHvXrMCufleODTz6RmfpSnHUPVqzaF-T0Pe33bR6IzriQpB1DnMd8HqtZ9bTb6A1HWodO1zVxseHpqQSEylSXeTPXdVmOZR9Xu5YNnmqX6SrRCy2z3-kEQD_hmKi261iVPiPmH3yZhxvaT33hgtIMQ",
                    "width": 4032
                }
            ],
            "place_id": "ChIJraTOUEngBnwRzO06t9A3GPw",
            "plus_code": {
                "compound_code": "3M3C+5J Kapa\u02bba, Hawaii",
                "global_code": "73J23M3C+5J"
            },
            "rating": 4.3,
            "reference": "ChIJraTOUEngBnwRzO06t9A3GPw",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 850,
            "vicinity": "440 Aleka Pl, Kapa\u02bba"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0529079,
                    "lng": -159.3294982
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.05470657989272,
                        "lng": -159.3283472701073
                    },
                    "southwest": {
                        "lat": 22.05200692010727,
                        "lng": -159.3310469298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Kauai Shores Hotel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3953,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/101824922630554566337\">Kauai Shores, an Aqua Hotel</a>"
                    ],
                    "photo_reference": "ATtYBwLB6sjf2IoL2WzRepUHNLUBusrJ5zQs8B2VOFPM1oRXvfZaG-HQ2rZwHPpJ8DHsel56EXXd41g1azcyzFHWA3AEI2ZFSvHqfgB67M5nILfaIHkkVyb7wPpzsJSsLtTIcR1Qh64oPOMWYIhz4GTzyZ1AmNXImnO2DJl1N9Pwu4LjTIY",
                    "width": 5850
                }
            ],
            "place_id": "ChIJm1J66UvgBnwRkWpVMYHWotA",
            "plus_code": {
                "compound_code": "3M3C+56 Kapa\u02bba, Hawaii",
                "global_code": "73J23M3C+56"
            },
            "rating": 4.2,
            "reference": "ChIJm1J66UvgBnwRkWpVMYHWotA",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 1179,
            "vicinity": "420 Papaloa Rd, Kapa\u02bba"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0563563,
                    "lng": -159.3255959
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.05754412989272,
                        "lng": -159.3243933201072
                    },
                    "southwest": {
                        "lat": 22.05484447010728,
                        "lng": -159.3270929798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Plantation Hale Suites",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 310,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/104046524608716337416\">Plantation Hale Suites</a>"
                    ],
                    "photo_reference": "ATtYBwIMYRI3Vkj2FNq0ugDjI_8msnpdRySBMxe_QlzB4f4L-KaiDd6Vxxcp0EBgwG-EPue8sQ7SadxAAso3pix2Q4XSjG923iCgWXTWOBD39J7G5JyigjyyRYbDQaKeQxiL20U6FEyf3Tq8Wnsm8cX60SflIizEHlFAy0NpdDQOlmN-dkub",
                    "width": 730
                }
            ],
            "place_id": "ChIJfyRCkk7gBnwROxwe08sH-g0",
            "plus_code": {
                "compound_code": "3M4F+GQ Kapa\u02bba, Hawaii",
                "global_code": "73J23M4F+GQ"
            },
            "rating": 4.1,
            "reference": "ChIJfyRCkk7gBnwROxwe08sH-g0",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 498,
            "vicinity": "525 Aleka Loop, Kapa\u02bba"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0357722,
                    "lng": -159.337025
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.03672607989272,
                        "lng": -159.3360485201072
                    },
                    "southwest": {
                        "lat": 22.03402642010728,
                        "lng": -159.3387481798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Kaha Lani Resort",
            "photos": [
                {
                    "height": 400,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/113469936590120499501\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwIOP5l2xe55elLfB6RrKjsDRybwihlwri824EWt3VXxD0rEP3YHL0rK0blYubKL3YzJaSHThtgF9yF4M1aJGDGdYUuUb11LSfHPmUpoLNqv93vmONMOyPFCfZJRGTgEXaFhNJcBySprDAhsLe59LuPnW7k7oS8xjQSn56o649sJfVO1",
                    "width": 600
                }
            ],
            "place_id": "ChIJs77G6dLhBnwRUSPxUGuCO14",
            "plus_code": {
                "compound_code": "2MP7+85 Lihue, Hawaii",
                "global_code": "73J22MP7+85"
            },
            "rating": 4.5,
            "reference": "ChIJs77G6dLhBnwRUSPxUGuCO14",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 251,
            "vicinity": "4460 Nehe Rd, Lihue"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0611338,
                    "lng": -159.3200187
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.06259322989272,
                        "lng": -159.3189326701073
                    },
                    "southwest": {
                        "lat": 22.05989357010728,
                        "lng": -159.3216323298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Waipouli Beach Resort",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 800,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/110826082844719477143\">Waipouli Beach Resort</a>"
                    ],
                    "photo_reference": "ATtYBwKkX2riWnvAnBWVu7gqxDkp3aJRC-QPKUflDwIt6C-Wcdw0ZBTsGJja2729wAhCvEMj6FNcr1wagz_hhKzqbjFzoXsa9ManNsR9IJe4BRqSRrwf4fiPLYmL_Gf-Ea88a3wy-1Cp8ZSybkLyIY8_JLQEJPdfwwEmAITAcsIkzIjnpIvg",
                    "width": 1200
                }
            ],
            "place_id": "ChIJPxhnNHbhBnwRXWMPCRsp3cU",
            "plus_code": {
                "compound_code": "3M6H+FX Kapa\u02bba, Hawaii",
                "global_code": "73J23M6H+FX"
            },
            "rating": 4.6,
            "reference": "ChIJPxhnNHbhBnwRXWMPCRsp3cU",
            "scope": "GOOGLE",
            "types": [
                "real_estate_agency",
                "travel_agency",
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 522,
            "vicinity": "4-820 Kuhio Hwy Suite 1, Kapa\u02bba"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0786593,
                    "lng": -159.3149317
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.08000912989273,
                        "lng": -159.3135818701072
                    },
                    "southwest": {
                        "lat": 22.07730947010728,
                        "lng": -159.3162815298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hotel Coral Reef",
            "photos": [
                {
                    "height": 1080,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/103289044753827306772\">Fiona Ryan</a>"
                    ],
                    "photo_reference": "ATtYBwIkh3uhW9bOl56QPM-uSAWdqO6zVStdhsvnZMn81bZzhQeVA1tXDJrCq3uWw9N7GfxwiTaWZhjkWw0lXwHEI7nw9F-se5-EwDF5vfC8lb3Vz9VIlSuwQXb8t_lwCCDi84KsKjvjTf5LW423TzX8eoPr57oTztA9_jE8BdCWudWGJrdF",
                    "width": 1920
                }
            ],
            "place_id": "ChIJC-tIXvLgBnwR4NS75_vdikQ",
            "plus_code": {
                "compound_code": "3MHP+F2 Kapa\u02bba, Hawaii",
                "global_code": "73J23MHP+F2"
            },
            "rating": 4.5,
            "reference": "ChIJC-tIXvLgBnwR4NS75_vdikQ",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 164,
            "vicinity": "4-1516 Kuhio Hwy, Kapa\u02bba"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0421759,
                    "lng": -159.3372009
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.04368877989272,
                        "lng": -159.3360118201073
                    },
                    "southwest": {
                        "lat": 22.04098912010728,
                        "lng": -159.3387114798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Aston Aloha Beach Hotel",
            "photos": [
                {
                    "height": 2448,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/106192228866263689586\">Michael Bork</a>"
                    ],
                    "photo_reference": "ATtYBwJiJPfBg3-dbngmIhWBZdIIH5KM8NEUKac9_pKzUDHMQeLi4-B3CtXAE4RlhQUUwZTwD7Q8wlCJ6aB2kZZR-a-Fk9mB6SkJ3EE0mDbG7K9DbuyoH0If5joPGym-gk3BPyN_SA9MvVze2e2oZ5fR08gpsfu8KaL4Dyk49Ob7FiFkNlAT",
                    "width": 3264
                }
            ],
            "place_id": "ChIJnWMsnMzhBnwRY-sUgUbp2Qs",
            "plus_code": {
                "compound_code": "2MR7+V4 Kapa\u02bba, Hawaii",
                "global_code": "73J22MR7+V4"
            },
            "rating": 2.9,
            "reference": "ChIJnWMsnMzhBnwRY-sUgUbp2Qs",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 27,
            "vicinity": "3-5920 Kuhio Hwy, Kapa\u02bba"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 22.0488754,
                    "lng": -159.3358205
                },
                "viewport": {
                    "northeast": {
                        "lat": 22.04956415000001,
                        "lng": -159.3345373201072
                    },
                    "southwest": {
                        "lat": 22.04680915,
                        "lng": -159.3372369798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Coco Palms Resort",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 1171,
                    "html_attributions": [

{
    "html_attributions": [],
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.59966,
                    "lng": 73.08155
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.5983125701072779,
                        "lng": 73.08289242989272
                    },
                    "southwest": {
                        "lat": -0.6010122298927223,
                        "lng": 73.08019277010727
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Abuharee Grand",
            "photos": [
                {
                    "height": 3980,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/114901575511447070791\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJfOrijRvXL2axY88oNckiyoBtb9SLMOhNinZmAS0fTwL8a8luI1-xIF-0rb3OO_v9ebGAfWOFDDqdzOnTGOJIwlbnwIg2rrzVa-AhtXz72rqBOo_zoGWr-rcprSxb-RspH9GF5BnJgVUzc2VUZE1GAvwii1ZEainvQRgEWI-Agu8PO",
                    "width": 5970
                }
            ],
            "place_id": "ChIJH_BhJiSgtSQRrnYzByw-8JA",
            "plus_code": {
                "compound_code": "C32J+4J Addu City, Maldives",
                "global_code": "6JFMC32J+4J"
            },
            "rating": 4.7,
            "reference": "ChIJH_BhJiSgtSQRrnYzByw-8JA",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 3,
            "vicinity": "Abuharee Grand, Addu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.6000744,
                    "lng": 73.0867851
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.5986972701072778,
                        "lng": 73.08817982989272
                    },
                    "southwest": {
                        "lat": -0.6013969298927223,
                        "lng": 73.08548017010729
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Pebbles Inn",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 1702,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/110583070957722887487\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwI2cIwhz-a1c6pUKwG1EZVkOe-DCyn8NfEIv1ur81sqOBfWQ3Ap2PAqfnWGqcJugB4rWGSW-9Ndtwb-yLo5tuCl-6d3IDZKH0EX6WvEOVF0g388vg67EtJWx0Sa9-DJfS9fO3rPSdh884RADTZY798mBTVHxgnUumfBM3yGDUR-NrtQ",
                    "width": 3024
                }
            ],
            "place_id": "ChIJD844dCegtSQREQLpRLo8irE",
            "plus_code": {
                "compound_code": "93XP+XP Addu City, Maldives",
                "global_code": "6JFM93XP+XP"
            },
            "rating": 4.6,
            "reference": "ChIJD844dCegtSQREQLpRLo8irE",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 47,
            "vicinity": "Link Road, Addu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.6198034,
                    "lng": 73.0987569
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.6184253701072777,
                        "lng": 73.10009077989272
                    },
                    "southwest": {
                        "lat": -0.6211250298927222,
                        "lng": 73.09739112010729
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Green Wing Guest House",
            "opening_hours": {
                "open_now": false
            },
            "photos": [
                {
                    "height": 3731,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/111474360802892912389\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwIfUts39xJubycRL_bkC48IIPdhrzCtdU8uh0yaVlfith-2PPxZat8T5i9pz0zLAFlZl4zFsnj9ZqGfP1t4BWlB3zT-iMhiDnQ_QTjMeK59Z39b1o4IEb1z9ktmQjuPhfJWgPh2LTN51vEEHpgbHWy3KuVKWEH0nhZoSBRaIMmy6igs",
                    "width": 5597
                }
            ],
            "place_id": "ChIJyTAn_5yftSQRF39c8In67lw",
            "plus_code": {
                "compound_code": "93JX+3G Addu City, Maldives",
                "global_code": "6JFM93JX+3G"
            },
            "rating": 5,
            "reference": "ChIJyTAn_5yftSQRF39c8In67lw",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 4,
            "vicinity": "Link Road Addu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.6144394,
                    "lng": 73.0900575
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.6131037201072779,
                        "lng": 73.09138272989273
                    },
                    "southwest": {
                        "lat": -0.6158033798927223,
                        "lng": 73.08868307010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Dhirey",
            "photos": [
                {
                    "height": 2304,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/118174258542873135429\">\u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u0424\u0430\u0434\u0435\u0435\u0432</a>"
                    ],
                    "photo_reference": "ATtYBwLEM2pdQWW7wNpXjdu_mEHy19PhQx7u8OfraAuSQ7-7KFMAP3ZKlGBbVkp1WNaPuq3eRmXXJDuizUw24ExQEGrcYwFxKduLKt8Xjn4UQUGxKpvA9nwS_f9N_Awhc0sqR1Ris_KOqa1i4zYb91ZnmjpxgeWaTCdnX6PrlOFTMM4EAapy",
                    "width": 4096
                }
            ],
            "place_id": "ChIJrfBJUH6ftSQRnqz8Vrw_Igk",
            "plus_code": {
                "compound_code": "93PR+62 Addu City, Maldives",
                "global_code": "6JFM93PR+62"
            },
            "rating": 5,
            "reference": "ChIJrfBJUH6ftSQRnqz8Vrw_Igk",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 10,
            "vicinity": "Heenaa Magu, Addu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.5956328,
                    "lng": 73.0810869
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.5944338701072778,
                        "lng": 73.08247012989273
                    },
                    "southwest": {
                        "lat": -0.5971335298927223,
                        "lng": 73.07977047010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Rekidhiye Inn",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 1800,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/102400636122002486306\">Georgi Petkov</a>"
                    ],
                    "photo_reference": "ATtYBwI3c_XpljerDEu376OgcqyOtoOXiUAlzFGDGcZTLTzmIGkCaGiv6rasyQ33QAgSIn4NrLI8N7c__kZV09mJR0gylVdJY3mSBvlqK3wKokj5dwRfxDA0pbKR8gtuY9pzCBafHGWwSEhi0arjhbaDmHRO3p_WicMKjnwI8nsiT4hwUArX",
                    "width": 4000
                }
            ],
            "place_id": "ChIJBQt0MiKgtSQRIjeQHLc5gfU",
            "plus_code": {
                "compound_code": "C33J+PC Addu City, Maldives",
                "global_code": "6JFMC33J+PC"
            },
            "rating": 3.6,
            "reference": "ChIJBQt0MiKgtSQRIjeQHLc5gfU",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 12,
            "vicinity": "Mauman, Sunset Hingun, Addu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.6000656,
                    "lng": 73.08679289999999
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.5988843201072777,
                        "lng": 73.08806802989271
                    },
                    "southwest": {
                        "lat": -0.6015839798927222,
                        "lng": 73.08536837010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Pebbles Inn",
            "photos": [
                {
                    "height": 1836,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/115383901993838047010\">Aslam Mohamed</a>"
                    ],
                    "photo_reference": "ATtYBwKKKFlXYS3_2GgwgTVBx6KBtGpltHmhOXpUVBnhOJHKECnfNY4C3rByulZuG1EKVxFT3cyi9y03w02VFhM2RiAj3ksgSJIUycxGQk4xIa4Bsw-qel1U3XZude0Eyg8DwgF7ViJbV6uMLH7Rm5wmINce6sli2JINJVN8d4l34YYkEAw4",
                    "width": 3264
                }
            ],
            "place_id": "ChIJm0FGdCegtSQROhSIBoU76x8",
            "plus_code": {
                "compound_code": "93XP+XP Addu City, Maldives",
                "global_code": "6JFM93XP+XP"
            },
            "rating": 5,
            "reference": "ChIJm0FGdCegtSQROhSIBoU76x8",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 3,
            "vicinity": "Addu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.6034539999999999,
                    "lng": 73.0891389
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.6020672201072779,
                        "lng": 73.09045007989272
                    },
                    "southwest": {
                        "lat": -0.6047668798927224,
                        "lng": 73.08775042010727
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Abuhary grand",
            "photos": [
                {
                    "height": 3024,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/117552780005342910261\">Radek Novotn\u00fd</a>"
                    ],
                    "photo_reference": "ATtYBwLAJmu083DUoSkg9E_-p5yv3J_1bXmzBPbjLTXSU2j9ykL8FzTfNQH2tn_uXO8JEow16H9l734hALMT-g4DtNNrqA5pzKBWKPVB5oFH8Dg4nI7Azb8PRchaX9TM78RGdG5GCAEly7nJ3sqq779vFAtfbeLv-4qfe3BRzQDz8IuAcDZo",
                    "width": 4032
                }
            ],
            "place_id": "ChIJSZ7s6YeftSQRP5qW8OBUN8c",
            "plus_code": {
                "compound_code": "93WQ+JM Addu City, Maldives",
                "global_code": "6JFM93WQ+JM"
            },
            "rating": 3.7,
            "reference": "ChIJSZ7s6YeftSQRP5qW8OBUN8c",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 14,
            "vicinity": "Cupid Goalhi, Addu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.6020428999999999,
                    "lng": 73.0869207
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.6006628201072778,
                        "lng": 73.08823582989272
                    },
                    "southwest": {
                        "lat": -0.6033624798927222,
                        "lng": 73.08553617010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Crystal View",
            "place_id": "ChIJEzbt7yegtSQREpT6NVK4COo",
            "plus_code": {
                "compound_code": "93XP+5Q Addu City, Maldives",
                "global_code": "6JFM93XP+5Q"
            },
            "rating": 2.5,
            "reference": "ChIJEzbt7yegtSQREpT6NVK4COo",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 2,
            "vicinity": "Sun Light Higun, Addu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.6096496,
                    "lng": 73.094109
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.6082894701072776,
                        "lng": 73.09546952989271
                    },
                    "southwest": {
                        "lat": -0.6109891298927221,
                        "lng": 73.09276987010726
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Cress Lodge",
            "photos": [
                {
                    "height": 3131,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/104133709651600341199\">ansar Moosa</a>"
                    ],
                    "photo_reference": "ATtYBwLUIFEkJrLly5DZOv36lW70fofjJJ2sLMwhA-Zt24DtCW6o9SDXdyo0w-ywFeNwszEAvnsZMwSamHiH43GD_sdlLXg2x2g0-Vsw4CuLNV1q-G2bKp92-zGoW2ZzqNRPBtvf-Il_kQ9nd9eOHO8_Q3aNfachX89H73KMO5lNlgWw1yiF",
                    "width": 4696
                }
            ],
            "place_id": "ChIJeV6gKYKftSQRkYeSBR8OFuM",
            "plus_code": {
                "compound_code": "93RV+4J Addu City, Maldives",
                "global_code": "6JFM93RV+4J"
            },
            "rating": 4.4,
            "reference": "ChIJeV6gKYKftSQRkYeSBR8OFuM",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 9,
            "vicinity": "Hithadhoo, Addu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.614653,
                    "lng": 73.08857019999999
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.6132893701072777,
                        "lng": 73.08994537989273
                    },
                    "southwest": {
                        "lat": -0.6159890298927222,
                        "lng": 73.08724572010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Bloomy Inn",
            "photos": [
                {
                    "height": 3516,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/109257772306760995676\">Raaif Mu-umin</a>"
                    ],
                    "photo_reference": "ATtYBwIcnF3Vo_jcCYNvJlvRSdboDKOGHiBgVfI1sau7etObXpuHL8SuithJvLBfSYlE2a5psfYPbH_nvoAu6pmZYqhGbGjO9XDlPijm797SVY4xYepc47xmswIU-tlipyVMG2WGN7nF8piI7KjJXF7ZD-hKVpTz8EoFBRcWDjtwAsZlL4T5",
                    "width": 2637
                }
            ],
            "place_id": "ChIJyV6byWOftSQRQfuRu5cVbAg",
            "plus_code": {
                "compound_code": "93PQ+4C Addu City, Maldives",
                "global_code": "6JFM93PQ+4C"
            },
            "rating": 5,
            "reference": "ChIJyV6byWOftSQRQfuRu5cVbAg",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 4,
            "vicinity": "Kandhuvalu Magu, Addu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.6133854,
                    "lng": 73.0890409
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.6120538201072778,
                        "lng": 73.09041637989273
                    },
                    "southwest": {
                        "lat": -0.6147534798927222,
                        "lng": 73.08771672010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Zayan Holiday Home",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 843,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/101892335802076921852\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwKdoq3oHGT7Rzzyfi90FLFdiLqMLklnnapB5BY0nYhbOCt3N3bsNs0LsdxUHVvr2UNy2OvHkZi5PWDZw345ckZ9qg92YAFRD82RTgtrJlTbn4F7_2XQngroIwd-nZ4dBT8xP2YyV4dNb5DV4oXGlnkWZUc-uWMppoRqFY6C0fYe4pVu",
                    "width": 1280
                }
            ],
            "place_id": "ChIJCXwcULqftSQRUnVc6nLCFaw",
            "plus_code": {
                "compound_code": "93PQ+JJ Addu City, Maldives",
                "global_code": "6JFM93PQ+JJ"
            },
            "rating": 5,
            "reference": "ChIJCXwcULqftSQRUnVc6nLCFaw",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 1,
            "vicinity": "Vali Maamiskiy Magu, Addu City"
        },
        {

{
    "html_attributions": [],
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.8677555,
                    "lng": -73.8283135
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.86644527010728,
                        "lng": -73.82700762010727
                    },
                    "southwest": {
                        "lat": -41.86914492989272,
                        "lng": -73.82970727989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hotel Balai",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 900,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/113632269200819351723\">Hotel Balai</a>"
                    ],
                    "photo_reference": "ATtYBwKGN6Q8WhCN2hwmv2uq0STo0tHtjX88Mkc2aU_BX987OZlr9jKQmQCKpd9x8cX9C7iAwSy0BT4ShfhSQhQH9FFy7-5o77iS52JeBUIenEN8FSncn_fwka1ND4YTYMhN_UD_GcWG_u_7EOm_MrA4NySXRYo4QQWSX6TNXmwVK5on_tUE",
                    "width": 1600
                }
            ],
            "place_id": "ChIJ7_H7iqeSIpYRqu-htSAv_m4",
            "plus_code": {
                "compound_code": "45JC+VM Ancud, Chile",
                "global_code": "47C845JC+VM"
            },
            "rating": 4.4,
            "reference": "ChIJ7_H7iqeSIpYRqu-htSAv_m4",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 100,
            "vicinity": "Pudeto 169, Ancud"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.862372,
                    "lng": -73.830086
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.86112937010728,
                        "lng": -73.82875572010728
                    },
                    "southwest": {
                        "lat": -41.86382902989272,
                        "lng": -73.83145537989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Panamericana Hotel Ancud",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 640,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/107327428816098802482\">Ancud Panamericana</a>"
                    ],
                    "photo_reference": "ATtYBwIJg6Fy0CFGsJEHBXkWhlIeEFfr163KjH8Wpxx6SqMc6RmAQ-J3z3h7JBUq255q4qOECDd-RQ9Rlu552zFUzZNWf4HG1FgbZoiViUN0vFb6gSj9H9h8iBP4xPX2FR__gy3kiBUkqIQy_gbR4rlbrI3BrDrPgvC4j8OryBJWzWBIYGZE",
                    "width": 960
                }
            ],
            "place_id": "ChIJg_XNiaiSIpYRf8zJ5YYB9lg",
            "plus_code": {
                "compound_code": "45Q9+3X Ancud, Chile",
                "global_code": "47C845Q9+3X"
            },
            "rating": 4.3,
            "reference": "ChIJg_XNiaiSIpYRf8zJ5YYB9lg",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "bar",
                "restaurant",
                "food",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 257,
            "vicinity": "San Antonio 30, Ancud"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.8598954,
                    "lng": -73.8205984
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.85871472010727,
                        "lng": -73.81932217010727
                    },
                    "southwest": {
                        "lat": -41.86141437989272,
                        "lng": -73.8220218298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
            "name": "Hostal Boutique Faros del Sur",
            "photos": [
                {
                    "height": 2336,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/113449361259914715004\">Marcela Bruna</a>"
                    ],
                    "photo_reference": "ATtYBwL2YsuZPakJErmhAbaREGt6TCfqyFT_JwMcLoocbZt2cvIP_SLsrbmuOKoT2lwlACj3BcUaI5PJECcxEHF-akDZOv0K8XiniGaCSuTeBwEin2HnnwCJG6keohUoBBUfsJDarOyfIL6ayOqz_o77lt01efI2KxzHFTKB_4KBKy0HO-ov",
                    "width": 4160
                }
            ],
            "place_id": "ChIJ49iws6mSIpYRrPVK_eh_w3A",
            "plus_code": {
                "compound_code": "45RH+2Q Ancud, Chile",
                "global_code": "47C845RH+2Q"
            },
            "rating": 4.4,
            "reference": "ChIJ49iws6mSIpYRrPVK_eh_w3A",
            "scope": "GOOGLE",
            "types": [
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 70,
            "vicinity": "Costanera Norte 320, Ancud"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.872489,
                    "lng": -73.8283119
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.87113627010728,
                        "lng": -73.82704962010727
                    },
                    "southwest": {
                        "lat": -41.87383592989273,
                        "lng": -73.82974927989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Vista al Mar Hostel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 810,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/116741387959252499358\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwKaEQL8sUsTsB6NtckXYGBQPdZj8PEf1FGrl7zwDOL0qzzMd3kuF5nh59Shuo7y9S6vaxq8hikPUBdbxJ19OR5l92Bg_hHb2gv600IjDGSOkV-Q59NKWQQ6uCxTso0DSUfB-pzbHeuIop4pCZhBvltkFp3uac_yPXJlgLIEBfJCpNkf",
                    "width": 1440
                }
            ],
            "place_id": "ChIJ07pKeFCNIpYRpzS0SfkUp7U",
            "plus_code": {
                "compound_code": "45HC+2M Ancud, Chile",
                "global_code": "47C845HC+2M"
            },
            "rating": 4.5,
            "reference": "ChIJ07pKeFCNIpYRpzS0SfkUp7U",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 211,
            "vicinity": "Avda. Costanera, Salvador Allende 918, Ancud"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.87112399999999,
                    "lng": -73.826506
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.86976167010728,
                        "lng": -73.82509862010727
                    },
                    "southwest": {
                        "lat": -41.87246132989272,
                        "lng": -73.82779827989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "13 Lunas Hostel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 1536,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/103379089975853373879\">13 Lunas Hostel</a>"
                    ],
                    "photo_reference": "ATtYBwJDMVB9ni9EuO1RVJ-6y6NDIDDohuUJSIWSkXKLz--1WJKG6D3C9wHtDXHTeSmOfDGExyEWlc4XgEh8kLPTVPrt_TcqpD5ioNcl8WSn93epy0Gpw2RpMB_4oxrlnBcriuO0GkhpcE6mpq2bU9n-2F7zPi-R_l3F3JmAZkO6IDQFxRo3",
                    "width": 2048
                }
            ],
            "place_id": "ChIJTwvoElmNIpYRXK-LlXEHBLc",
            "plus_code": {
                "compound_code": "45HF+H9 Ancud, Chile",
                "global_code": "47C845HF+H9"
            },
            "rating": 4.7,
            "reference": "ChIJTwvoElmNIpYRXK-LlXEHBLc",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 189,
            "vicinity": "Los Carrera 855, Ancud"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.8713436,
                    "lng": -73.8262537
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.86999302010727,
                        "lng": -73.82490047010728
                    },
                    "southwest": {
                        "lat": -41.87269267989272,
                        "lng": -73.82760012989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "HOSPEDAJE ANCUD VISTA AL MAR",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3120,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/116775068651719561221\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJA_NfHllw-0OMYMiSe7BqM-uTzZrya17BBs4608uWMVxqoQa7nxhmuYkdmM--N6lIVpnYD6M_JpSjTWt56fQ6_uqbMr5wf-NO8FHOBduvJhfDgHiCi7SSbzhlU8OF560LFjPaS2-ysAz4GOryPh07SY2GQJ0dnbEvtx1Bpf86flMqI",
                    "width": 4160
                }
            ],
            "place_id": "ChIJ_bkYQa6NIpYR08ekJfKXIz0",
            "plus_code": {
                "compound_code": "45HF+FF Ancud, Chile",
                "global_code": "47C845HF+FF"
            },
            "rating": 0,
            "reference": "ChIJ_bkYQa6NIpYR08ekJfKXIz0",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 0,
            "vicinity": "Los Carrera 916 A, Ancud"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.8694565,
                    "lng": -73.82162430000001
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.86801287010728,
                        "lng": -73.82026262010729
                    },
                    "southwest": {
                        "lat": -41.87071252989273,
                        "lng": -73.82296227989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hosting \"The Calafates\"",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3000,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/115516034084148322483\">Rodolfo Maximiliano ORTEGA</a>"
                    ],
                    "photo_reference": "ATtYBwJikCRegNr9wGEEj1kFLnYzQJRA9lL76mjm4ugyIlpIFOkU_3ty-KleNvOKroW6YOQ7oHtOKCrdLHlc1lMm2lf5aVyGWOG2CRdHWiPDf1GkY4IIgaEARY229CxpugYvqFpm56HRYEVS-OwTrl1gLHWVvHYrPnTVnFc2dmLsxYikC4D_",
                    "width": 4000
                }
            ],
            "place_id": "ChIJE48n_16NIpYRjrfd3ENbcAk",
            "plus_code": {
                "compound_code": "45JH+69 Ancud, Chile",
                "global_code": "47C845JH+69"
            },
            "rating": 4.7,
            "reference": "ChIJE48n_16NIpYRjrfd3ENbcAk",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 85,
            "vicinity": "An\u00edbal Pinto 531, Ancud"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.8603579,
                    "lng": -73.8224189
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.85907907010728,
                        "lng": -73.82102207010728
                    },
                    "southwest": {
                        "lat": -41.86177872989273,
                        "lng": -73.82372172989271
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hotel Arena Gruesa",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 699,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/104721234284050216496\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwIM3PIn_z6k13kM4nZSOP40klXo8BA3gezwUvkYH2_EwWHOfdL1z3tqd36uK2_6Hv24npNkgMYnryZ76DB_ihieTbvQ3US4mkyPY9Q_Fa2JZy83-UYolVG_hS3qfL77VuZ6Mvf1AtctQAWXnJv8awzUk5Y7IFHJbrjZUjrHpHlMOumL",
                    "width": 1024
                }
            ],
            "place_id": "ChIJWfyEuqOSIpYRCJRKMEmFo8U",
            "plus_code": {
                "compound_code": "45QH+V2 Ancud, Chile",
                "global_code": "47C845QH+V2"
            },
            "rating": 4.3,
            "reference": "ChIJWfyEuqOSIpYRCJRKMEmFo8U",
            "scope": "GOOGLE",
            "types": [
                "campground",
                "lodging",
                "park",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 44,
            "vicinity": "Costanera Nte. 290, Ancud"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.87172169999999,
                    "lng": -73.828236
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.87037432010727,
                        "lng": -73.82699032010727
                    },
                    "southwest": {
                        "lat": -41.87307397989272,
                        "lng": -73.82968997989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "HOTEL ANCUD DON LUCAS",
            "photos": [
                {
                    "height": 1067,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/115343887750804675994\">HOTEL DON LUCAS</a>"
                    ],
                    "photo_reference": "ATtYBwLO_iIar36XdrdhEVpANo_cpX8-qY-AlGH7Ge1ycVvduTA1-XiqtErrMNAe_z8ZzTf_gHBYO2Qov4p7Go-nnuMMbit5ORxKHAfJDQN8bTI72xfBcR3KrnulVslacXPLYWWvkxOGziqL1lSBPXqg_p2rJ1P5IZSh8_RAHXkWCxhB-sZ6",
                    "width": 1600
                }
            ],
            "place_id": "ChIJKSJdiFmNIpYRkOh5e5L_VMk",
            "plus_code": {
                "compound_code": "45HC+8P Ancud, Chile",
                "global_code": "47C845HC+8P"
            },
            "rating": 4.1,
            "reference": "ChIJKSJdiFmNIpYRkOh5e5L_VMk",
            "scope": "GOOGLE",
            "types": [
                "spa",
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 177,
            "vicinity": "Costanera 906, Ancud"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.8689484,
                    "lng": -73.823784
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.86759277010728,
                        "lng": -73.82245632010729
                    },
                    "southwest": {
                        "lat": -41.87029242989272,
                        "lng": -73.82515597989273
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hospedaje Ayelen",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2736,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/110324713919933635775\">Alejandra Flores</a>"
                    ],
                    "photo_reference": "ATtYBwJ692-_MujPYD1_uOic-NhXsHLOcJBqQMQMfx6uk2BA8ZtAHc9mxtWtQy7e21atNPkZteJq-Q3r7bsLNNqx57m13zRbBGG4a0ZqQzCFm0hrP3RCk1lsTp-_JRKxpT5RtzGsUGRHYZI5m7x5CQxeSyztHHOG2pd1MgnmQ_bzBK8we41b",
                    "width": 3648
                }
            ],
            "place_id": "ChIJJwrsLl-NIpYRvZ35XP9alnA",
            "plus_code": {
                "compound_code": "45JG+CF Ancud, Chile",
                "global_code": "47C845JG+CF"
            },
            "rating": 4.6,
            "reference": "ChIJJwrsLl-NIpYRvZ35XP9alnA",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 40,
            "vicinity": "Goycolea 559, Ancud"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -41.865334,
                    "lng": -73.830635
                },
                "viewport": {
                    "northeast": {
                        "lat": -41.86396177010727,
                        "lng": -73.82937627010728
                    },
                    "southwest": {
                        "lat": -41.86666142989272,
                        "lng": -73.83207592989271
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "HOSTAL LLUHAY",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {

{
    "html_attributions": [],
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 3.758288,
                    "lng": 72.966692
                },
                "viewport": {
                    "northeast": {
                        "lat": 3.759622979892722,
                        "lng": 72.96808147989272
                    },
                    "southwest": {
                        "lat": 3.756923320107278,
                        "lng": 72.96538182010727
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Noovilu Suites - The luxury guest house in Maldives",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 405,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/112016258849724739738\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwID7s3sr0DK3NXwnNJI5figTqp3jMseb-VSns1zlhXH2iGLMcpMGCKcq6sGiFiQ0mjS49FVlsQ6AkLp4lBmP5X1Rv_13tLmamlzLlcNzt3bO1jx9LWoAuku9Fl4D618mCkBTD_VOYleaHRYsDeE6z_nnS5-fDmjtrEJL5B1dpydewXV",
                    "width": 720
                }
            ],
            "place_id": "ChIJbccQ4r7FQDsREKFXm85EoOU",
            "plus_code": {
                "compound_code": "QX58+8M Mahibadhoo, Maldives",
                "global_code": "6JMJQX58+8M"
            },
            "rating": 4.7,
            "reference": "ChIJbccQ4r7FQDsREKFXm85EoOU",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "store",
                "establishment"
            ],
            "user_ratings_total": 40,
            "vicinity": "Asaree Hingun Mahibadhoo"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 3.7908373,
                    "lng": 72.9613722
                },
                "viewport": {
                    "northeast": {
                        "lat": 3.792148579892722,
                        "lng": 72.96270042989272
                    },
                    "southwest": {
                        "lat": 3.789448920107279,
                        "lng": 72.96000077010727
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Kirulhiya Maldives",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2604,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/110329251169932538885\">Debojit Das</a>"
                    ],
                    "photo_reference": "ATtYBwKFacZGn_VTd4331oBQjCNBVqlkRnCTxeFrFIomuvH7ZM5T5dHXxl4mot2WGXPssSiQnNdAzUWNsJUNtl5hX98C5yTBGYpxYRP10E6E3hQXupJ5-SrZ-u0QPi_E996Il6D4d57hid6IDOqd4MiJgSwSgWqNGCW9BfzcrXkKZSB0r7sm",
                    "width": 4624
                }
            ],
            "place_id": "ChIJbyRwpUPEQDsR7dSqd5uMpBo",
            "plus_code": {
                "compound_code": "QXR6+8G Omadhoo, Maldives",
                "global_code": "6JMJQXR6+8G"
            },
            "rating": 4.7,
            "reference": "ChIJbyRwpUPEQDsR7dSqd5uMpBo",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 36,
            "vicinity": "Vashai Magu, Omadhoo"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 3.7921349,
                    "lng": 72.9622546
                },
                "viewport": {
                    "northeast": {
                        "lat": 3.793488929892721,
                        "lng": 72.96360522989272
                    },
                    "southwest": {
                        "lat": 3.790789270107278,
                        "lng": 72.96090557010729
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hudhuveli Maldives",
            "photos": [
                {
                    "height": 3024,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/117248390714638382143\">\u4f73\u84c9</a>"
                    ],
                    "photo_reference": "ATtYBwLioGR6v8i0uCgLt0-X4MptJsLp7-am82iIVAkfa9p008vNeOEYmLEC0Akrbcdp4IgBuBJ8j9bb1JVj2aEdW8QkiuI200BgKzYB0sAuFWszVrtkGGLMLSlQNI-uNCWSDbyJ3d13AJm5lZTTdRldkq3So2m4pzkZq1PaWtC28PhnONce",
                    "width": 4032
                }
            ],
            "place_id": "ChIJjVYMaHjFQDsRIUwaXjarAwk",
            "plus_code": {
                "compound_code": "QXR6+VW Omadhoo, Maldives",
                "global_code": "6JMJQXR6+VW"
            },
            "rating": 5,
            "reference": "ChIJjVYMaHjFQDsRIUwaXjarAwk",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 7,
            "vicinity": "Ameenee Magu, Omadhoo"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 3.7571682,
                    "lng": 72.972511
                },
                "viewport": {
                    "northeast": {
                        "lat": 3.758512329892722,
                        "lng": 72.97389187989272
                    },
                    "southwest": {
                        "lat": 3.755812670107278,
                        "lng": 72.97119222010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Liberty Guest House",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 4032,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/104081166496413632182\">Valentina Rutigliano</a>"
                    ],
                    "photo_reference": "ATtYBwJ8sX9IjMHYJSKqSjzxgaTXXxDcHV0zl8ixZ5X784ZDnkohRFKoo0VkMEJrBGbbUy9a6QItYG1IeSB3yFFhCRxbx5qgl1Qu7rSIWKAglw2xSkxUzIsfRIYi1aI9WItomYyIweVHxWJpMJ4y3qGKGxsYePJXo9uXdSLpTwOctFqoXs_4",
                    "width": 3024
                }
            ],
            "place_id": "ChIJdYWlVMDFQDsRLOQ8wPxMD4Q",
            "plus_code": {
                "compound_code": "QX4F+V2 Mahibadhoo, Maldives",
                "global_code": "6JMJQX4F+V2"
            },
            "rating": 4.5,
            "reference": "ChIJdYWlVMDFQDsRLOQ8wPxMD4Q",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "restaurant",
                "food",
                "point_of_interest",
                "store",
                "establishment"
            ],
            "user_ratings_total": 45,
            "vicinity": "Irumathee Magu, Mahibadhoo"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 3.757026799999999,
                    "lng": 72.96667459999999
                },
                "viewport": {
                    "northeast": {
                        "lat": 3.758411979892721,
                        "lng": 72.96793412989273
                    },
                    "southwest": {
                        "lat": 3.755712320107277,
                        "lng": 72.96523447010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Goby Lodge",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 4032,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/109491845230612855806\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJhzZiDZRN2TNwOYW0VOs8en2kS5VqWIbmzsUbMzFLiQwRxK_9fMMrQ1cKSoTqqOODjavj5T7I9XLp9TBMP2vPiW7178XD3BKUHF6Ewgvot9hmnX1UZoJD7cFZNRtxe5FQN2_TquPYOBDZEQGBVanNlDUYg_6_cxY9gMW1JRCuTtGk",
                    "width": 3024
                }
            ],
            "place_id": "ChIJAQKAqL_FQDsRfe0XAfC0dl0",
            "plus_code": {
                "compound_code": "QX48+RM Mahibadhoo, Maldives",
                "global_code": "6JMJQX48+RM"
            },
            "rating": 4.7,
            "reference": "ChIJAQKAqL_FQDsRfe0XAfC0dl0",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 3,
            "vicinity": "Western Neighborhood Mahibadhoo Alifu Dhaalu North Central Province"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 3.7915203,
                    "lng": 72.9606434
                },
                "viewport": {
                    "northeast": {
                        "lat": 3.792860579892722,
                        "lng": 72.96199157989273
                    },
                    "southwest": {
                        "lat": 3.790160920107278,
                        "lng": 72.95929192010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Turtle Maldives",
            "photos": [
                {
                    "height": 2592,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/116620692109102857498\">info</a>"
                    ],
                    "photo_reference": "ATtYBwK_pOkGfTWl3G6AqX46EOavLennlHk4SjVMdICENyXdHVsONzfISUcbyR_MGENDexOIbXq_XxBRlNHCRExF5QK5FkmdrLl_DN38Fhpa6AmtS-_jj6VEsaSrBb3x7CCgUae5ilAzTETV6yLOn-JeObQx5ISJ2Ap5WQIZOkpCJAU0qNni",
                    "width": 4608
                }
            ],
            "place_id": "ChIJySNZPzHFQDsRE15rYQCaLRU",
            "plus_code": {
                "compound_code": "QXR6+J7 Omadhoo, Maldives",
                "global_code": "6JMJQXR6+J7"
            },
            "rating": 5,
            "reference": "ChIJySNZPzHFQDsRE15rYQCaLRU",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 3,
            "vicinity": "Magu 1, Omadhoo"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 3.7921923,
                    "lng": 72.9637379
                },
                "viewport": {
                    "northeast": {
                        "lat": 3.793516829892722,
                        "lng": 72.96508047989272
                    },
                    "southwest": {
                        "lat": 3.790817170107279,
                        "lng": 72.96238082010727
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Nemo Inn",
            "photos": [
                {
                    "height": 719,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/116696261044434910523\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwIw2-GT5BKh7Why3H9D3-F414vPT77p-ajnV681g4-iPIuOPxhy1uNcToHrqAedk-54HEVAiZ5J0OyrowgtLvFF95SiWVtSRq5ngMuOlCdpkIR7Ps9nMBXAdScitiAtsAq2gEWqvTINBkBNNL2ihgvi_pVOC7AMXOkQ8WBLMEh2CTFJ",
                    "width": 1280
                }
            ],
            "place_id": "ChIJl194J0LEQDsRWMqFUBWSKvU",
            "plus_code": {
                "compound_code": "QXR7+VF Omadhoo, Maldives",
                "global_code": "6JMJQXR7+VF"
            },
            "rating": 4.8,
            "reference": "ChIJl194J0LEQDsRWMqFUBWSKvU",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 23,
            "vicinity": "Omadhoo"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 3.75788,
                    "lng": 72.969217
                },
                "viewport": {
                    "northeast": {
                        "lat": 3.759208029892722,
                        "lng": 72.97061217989273
                    },
                    "southwest": {
                        "lat": 3.756508370107278,
                        "lng": 72.96791252010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "MEHEL holiday home",
            "photos": [
                {
                    "height": 3024,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/118105144617246122228\">pinhuei chen</a>"
                    ],
                    "photo_reference": "ATtYBwISWbjOyAwx1Raj5V1n8C00nAPT9nVg_6LO2jxpsyouQm75FCviR7xBIdwKISunEo6fkUxnwPrK5yWFGqPJ1zZnckjniItMUd1mBsOAUo0CD7fjkm6ue97qa6DV4b8RTYonw0EW0rmgvxc9Z_ymHlbGJlK_HJW6bjWgwr2-cLTL2Xf_",
                    "width": 4032
                }
            ],
            "place_id": "ChIJQ98Y8-7FQDsRmVa9Ba7WpNs",
            "plus_code": {
                "compound_code": "QX59+5M Mahibadhoo, Maldives",
                "global_code": "6JMJQX59+5M"
            },
            "rating": 4.8,
            "reference": "ChIJQ98Y8-7FQDsRmVa9Ba7WpNs",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 5,
            "vicinity": "Sosun Magu, Mahibadhoo"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 3.791193,
                    "lng": 72.9609296
                },
                "viewport": {
                    "northeast": {
                        "lat": 3.792561979892721,
                        "lng": 72.96228307989271
                    },
                    "southwest": {
                        "lat": 3.789862320107277,
                        "lng": 72.95958342010728
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Noomuraka Inn",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3024,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/104014048810867478353\">Abdulla Nooh</a>"
                    ],
                    "photo_reference": "ATtYBwK-cyre5RwZGaqJ3z3B8T1i5w1fxNRpTnSAcx2obKbrsjcP9ld8Dd4xC7UQXsXF9Og3-ixdlg-j5XrAeLNRhnPx8MwH0KDYH2hs0Q0N3nPH85hYrCzPVKL-gE72KC5b6AVPzZNSYk5q5WbsTBzrBzcdPBclba0drkGXSa242XdpQkZK",
                    "width": 4032
                }
            ],
            "place_id": "ChIJCT5cqkPEQDsRlXHDyO0R7z8",
            "plus_code": {
                "compound_code": "QXR6+F9 Omadhoo, Maldives",
                "global_code": "6JMJQXR6+F9"
            },
            "rating": 4.7,
            "reference": "ChIJCT5cqkPEQDsRlXHDyO0R7z8",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 13,
            "vicinity": "Orchid Magu, Omadhoo"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 3.7918678,
                    "lng": 72.9617655
                },
                "viewport": {
                    "northeast": {
                        "lat": 3.793225379892721,
                        "lng": 72.96308287989274
                    },
                    "southwest": {
                        "lat": 3.790525720107278,
                        "lng": 72.96038322010729
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Scuba Inn",
            "opening_hours": {
                "open_now": false
            },
            "photos": [
                {
                    "height": 2771,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/111705600695948863842\">zain Abdul Hannan</a>"
                    ],
                    "photo_reference": "ATtYBwLRO-i5GAKaIJqAtKYa20YaGPK4aD7nSnJY4zX45NVt8vNTzW-rpZINBkx0jGM47mYIRWxoPCmoVWtTRnYbbjSQHSJOWXDBxSZ4FMra1uuUFMShoqIuR0Le7Uc_YvgkfJ4zV2nLpZX1_O--9-XrkEhj6G2jJpCntWB_SriGO7bcUitX",
                    "width": 4980
                }
            ],
            "place_id": "ChIJKah8TkLEQDsRG4VqvYPUrnc",
            "plus_code": {
                "compound_code": "QXR6+PP Omadhoo, Maldives",
                "global_code": "6JMJQXR6+PP"
            },
            "rating": 5,
            "reference": "ChIJKah8TkLEQDsRG4VqvYPUrnc",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 29,
            "vicinity": "Omadhoo"
        }
    ],
    "status": "OK"
}

{
    "html_attributions": [],
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.1553145,
                    "lng": -175.1771504
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.15379937010728,
                        "lng": -175.1758084201073
                    },
                    "southwest": {
                        "lat": -21.15649902989272,
                        "lng": -175.1785080798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Paradise First Hotel",
            "place_id": "ChIJB52qqu6j9HERTiGNr106F1I",
            "plus_code": {
                "compound_code": "RRVF+V4 Nuku'alofa, Tonga",
                "global_code": "52C6RRVF+V4"
            },
            "rating": 5,
            "reference": "ChIJB52qqu6j9HERTiGNr106F1I",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 1,
            "vicinity": "Bay of Manumataongo, Nuku'alofa"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.1541772,
                    "lng": -175.2242193
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.15287257010728,
                        "lng": -175.2228811201073
                    },
                    "southwest": {
                        "lat": -21.15557222989272,
                        "lng": -175.2255807798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Dayspring Lodge",
            "photos": [
                {
                    "height": 1200,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/112081133121336112774\">Selina Lekeleka</a>"
                    ],
                    "photo_reference": "ATtYBwJMTRb44Hf6LpiKXueAOdNAy1FAP9_WALf__X3ONdle24xIkuZLwfqDKuqpX_ZRPl9PJ7fNMxnLDLqsJ30PpUFb8rggdIFkJKMBqmoAtWouud1Dv0ItDlNynOnmO2QjLUSME-7ahpqm-iNIOD5YxgmDuf1R114KAjUtwI_15xDAS3tE",
                    "width": 1600
                }
            ],
            "place_id": "ChIJQTZLMrej9HER2DYen5aL7ns",
            "plus_code": {
                "compound_code": "RQWG+88 Nuku'alofa, Tonga",
                "global_code": "52C6RQWG+88"
            },
            "rating": 5,
            "reference": "ChIJQTZLMrej9HER2DYen5aL7ns",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 2,
            "vicinity": "4 Vahaakolo Rd, Nuku'alofa"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.1539894,
                    "lng": -175.2286402
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.15269542010728,
                        "lng": -175.2271763201072
                    },
                    "southwest": {
                        "lat": -21.15539507989272,
                        "lng": -175.2298759798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Green Lodge Holiday Homes",
            "place_id": "ChIJbdDbDrOj9HERevGdSh24A_U",
            "plus_code": {
                "compound_code": "RQWC+CG Nuku'alofa, Tonga",
                "global_code": "52C6RQWC+CG"
            },
            "rating": 0,
            "reference": "ChIJbdDbDrOj9HERevGdSh24A_U",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 0,
            "vicinity": "Nuku'alofa, PO Box 1494, Nuku'alofa"
        }
    ],
    "status": "OK"
}
{
    "html_attributions": [],
    "next_page_token": "ATtYBwLy17JMR4nn4-hvHAAeKe2rhd2RY8tx31xdV_SurbrMWm8_WOkHiA-2tMySzsJB-7aGvly97rPkAm3nDDdWRC6BmzoaPLl1GgQX1m0LppmOA1UsxUnXuluLHMi8PRWEN3GlqZtI7SG490ygYVF5feAOnAAKw-qCAj_obKbAhM2EjL35yvLBLWuWOTZuJRplR_2DO3qXHsJ7ymVXJceFt572FSlW44tWaL9IauYDqtZXS2dIlg619gUbtPV4UFGypBdj7Y7n1WxNEL5dcYEkEMkTgs63y4UiqO32PqyWGmHZQjGnlltvWlJfZ1BeKo9lSQMJJUK8mlGwUPUruHIiK2OQk1sGP5PBrTb06tFE_Ev03dQK9rpvL7DbU7DDbqMrnUn4yYNFuDtHxU5vRk1KYmx90NM32sE6Attc0Wyun6-i9yn_JfQX0ThtJbbFoVQ",
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.4231701,
                    "lng": 100.3357086
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.424506329892721,
                        "lng": 100.3370552798927
                    },
                    "southwest": {
                        "lat": 5.421806670107277,
                        "lng": 100.3343556201073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Eastern & Oriental Hotel, Penang",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2272,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/106909407275279117010\">yokouchi wataru</a>"
                    ],
                    "photo_reference": "ATtYBwL--GwDe-sOs5xK20rZAZpOE2I9nLFDdgWYRFceEfl5zPFI_DQDrnwwwQ32DT2FuLvJjk82n3n8B3E7epjXAI3eB7nQ81-IWr9Sttmh6zcfpV5tIfxlUWS4CpxiLTIE0CQSwwNsR1lIHWXthCyv3jRtYA2qUibnh-2y-PdLORZvcaYM",
                    "width": 4032
                }
            ],
            "place_id": "ChIJqwgwB5vDSjAR-_JigEODOw8",
            "plus_code": {
                "compound_code": "C8FP+77 George Town, Penang, Malaysia",
                "global_code": "6PQ2C8FP+77"
            },
            "rating": 4.6,
            "reference": "ChIJqwgwB5vDSjAR-_JigEODOw8",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 2588,
            "vicinity": "10, Lebuh Farquhar, George Town"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.4163575,
                    "lng": 100.3430302
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.417736529892722,
                        "lng": 100.3444122798927
                    },
                    "southwest": {
                        "lat": 5.415036870107278,
                        "lng": 100.3417126201073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "The Prestige Hotel Penang",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3056,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/100001291202274610961\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwIUU3441O-OKrle-yA0iXXQOv9LbfxZDnG3co6wwtLQTYw5dmMjactzXr9m_gyl7dRf1A9vYGJR3sYVACEc2mfLaBn4FGfOg0KwzaRLvAtweO4vQzC8i_aFKjsYc4QUFvraq43G-7ZWDzMDbFHC1B5HX-jXndDKX0Z02YO12_uVt_JK",
                    "width": 4592
                }
            ],
            "place_id": "ChIJpR8nyenDSjARKNtv-set64A",
            "plus_code": {
                "compound_code": "C88V+G6 George Town, Penang, Malaysia",
                "global_code": "6PQ2C88V+G6"
            },
            "rating": 4.6,
            "reference": "ChIJpR8nyenDSjARKNtv-set64A",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 513,
            "vicinity": "8, Gat Lebuh Gereja, George Town"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.4193981,
                    "lng": 100.3189833
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.420675429892721,
                        "lng": 100.3203224298927
                    },
                    "southwest": {
                        "lat": 5.417975770107277,
                        "lng": 100.3176227701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Macalister Mansion",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 1246,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/109507939764513605560\">Sean Tan</a>"
                    ],
                    "photo_reference": "ATtYBwL36R50lHC82JpEvohzkxdxtO-9wvkozg3LzxsyxgS9pVUn2AcEpW-A2aNzxTrzdx-RA8CYz-bRdbvW__M-zF4AfFmV7ayPLyOX0a3hoA0MVW3d8xvz3UVuEwIcLi9arjvvck9pfutRYPpzn81PTWkY31Gyr-7AQcka9s0yElkVPDSI",
                    "width": 2048
                }
            ],
            "place_id": "ChIJGS8X47rDSjARQ2QDNSfIDXU",
            "plus_code": {
                "compound_code": "C899+QH George Town, Penang, Malaysia",
                "global_code": "6PQ2C899+QH"
            },
            "rating": 4.3,
            "reference": "ChIJGS8X47rDSjARQ2QDNSfIDXU",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 374,
            "vicinity": "228, Jalan Macalister, George Town"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.420737,
                    "lng": 100.334877
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.422242279892721,
                        "lng": 100.3361241298927
                    },
                    "southwest": {
                        "lat": 5.419542620107277,
                        "lng": 100.3334244701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "The Edison George Town, Penang",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3640,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/104927199672870843627\">Chris Cheng</a>"
                    ],
                    "photo_reference": "ATtYBwKTRBAV3e1NWfWA8BIOTWRiHFOo7EoVFlko3dZI5HGM72MOLifufApViQo9ekqMY1kTXKzhYnTdTXaxuz1LjARX6fuq4cgjan4PpOm1kU1lSuWWRxT7r2pCx0WGaYYXr-jHHLKzIfKfy7TLymiiusA4MkIvw01mQmJbbV1-XzaT-fyz",
                    "width": 2976
                }
            ],
            "place_id": "ChIJBzF3DJrDSjAR2q-IFv4FMNs",
            "plus_code": {
                "compound_code": "C8CM+7X George Town, Penang, Malaysia",
                "global_code": "6PQ2C8CM+7X"
            },
            "rating": 4.7,
            "reference": "ChIJBzF3DJrDSjAR2q-IFv4FMNs",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 241,
            "vicinity": "15, Lebuh Leith, George Town"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.4355512,
                    "lng": 100.3099313
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.436787029892723,
                        "lng": 100.3112079798927
                    },
                    "southwest": {
                        "lat": 5.434087370107278,
                        "lng": 100.3085083201073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "G Hotel Kelawai",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 1360,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/100340486317413635637\">G Hotel Kelawai</a>"
                    ],
                    "photo_reference": "ATtYBwJg1DVxFcB2lOxyqt9Tin0alF4zhF3qVojCcnkxhvunc6icn7KDL0ijwr-1SfPUk0Lu44hcB7g0tA8i_qUia0XIV23NqXSvWw0NoBaMFBpfNy_1qQbYQ2a69jAgFgIiut0fm9NZdkL1fHAaonGA8oYaygrTnniVx3FNw2C9e1IBboOr",
                    "width": 2048
                }
            ],
            "place_id": "ChIJT_-vTwHDSjAROYc7--YwMNw",
            "plus_code": {
                "compound_code": "C8P5+6X George Town, Penang, Malaysia",
                "global_code": "6PQ2C8P5+6X"
            },
            "rating": 4.5,
            "reference": "ChIJT_-vTwHDSjAROYc7--YwMNw",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 1830,
            "vicinity": "2, Persiaran Maktab, George Town"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.420772299999999,
                    "lng": 100.3337557
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.422114029892721,
                        "lng": 100.3350985798927
                    },
                    "southwest": {
                        "lat": 5.419414370107277,
                        "lng": 100.3323989201073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "The Southern Boutique Hotel",
            "opening_hours": {
                "open_now": false
            },
            "photos": [
                {
                    "height": 912,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/107259703584035645214\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwI0SiQJ_30KdYkvKjIhZPrlYxjRAag-_grQGjxEXo-W6U_-AxH_P85emX1NGxbU3wNWMkUh3Bde0tNJtv0V99XcGO2uD6ckjSW7ZvMHZDvtHCF32iiObIzd0fOSEGG4weWRLYAQvRQWFQSDg9WuiKbwige9ucrzD21SUE5CD76rAoZk",
                    "width": 1368
                }
            ],
            "place_id": "ChIJud02D5rDSjAR_LbinLBKp6E",
            "plus_code": {
                "compound_code": "C8CM+8G George Town, Penang, Malaysia",
                "global_code": "6PQ2C8CM+8G"
            },
            "rating": 4.1,
            "reference": "ChIJud02D5rDSjAR_LbinLBKp6E",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 136,
            "vicinity": "108, Muntri St, Georgetown, George Town"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.417395,
                    "lng": 100.330138
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.41878292989272,
                        "lng": 100.3314436798927
                    },
                    "southwest": {
                        "lat": 5.416083270107277,
                        "lng": 100.3287440201073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Areca Hotel Penang",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2177,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/111675437383384223313\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJhUq3KOWypjMKev97wxoBWJvPQ0kBP40WOKJ2xOZJ3MDajFkHqJMlDD856EdeMwAfCF97rTFMbYdRxsNqllHXftk-ITrMBb6nvq_cuQen5r_Ib7IoXBQkNGmzzMi8VukJemzyTNDAYsuFo1bpRKW5dTVg9azaMs9lW61EnOflbrT7z",
                    "width": 3870
                }
            ],
            "place_id": "ChIJKYY__5bDSjAR-R5wpSK-40g",
            "plus_code": {
                "compound_code": "C88J+X3 George Town, Penang, Malaysia",
                "global_code": "6PQ2C88J+X3"
            },
            "rating": 4.5,
            "reference": "ChIJKYY__5bDSjAR-R5wpSK-40g",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 380,
            "vicinity": "5, Jalan Khoo Sian Ewe, George Town"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.4116946,
                    "lng": 100.3314997
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.413002229892722,
                        "lng": 100.3328284298927
                    },
                    "southwest": {
                        "lat": 5.410302570107278,
                        "lng": 100.3301287701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Noordin Mews",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 4912,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/102648027391252752005\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJtOjs5KsCqnR4TN-ULr_Z9OX2oNld9mW0w8lxYiMzZDuqAdaXb1NdhGiDStse5-wrSHdLIS3yBJhhThZn7QtDdie8iiaoVc5hOMO89JxZqi8FicOH2RTLft13XJHu1yiLPedrFD-T6PTmUqevkNs2HYY1kFEz_Suxz4DsjH0owC10d",
                    "width": 7361
                }
            ],
            "place_id": "ChIJT1-h65TDSjARYL8xoRi_rIg",
            "plus_code": {

{
    "html_attributions": [],
    "results": [],
    "status": "ZERO_RESULTS"
}
{
    "html_attributions": [],
    "next_page_token": "ATtYBwKYu8cDyT8chlUQf9CZctx8nQkotCWHnWEMOwxHWyukU80gV6qn-qtRRjfj_0HzgodghOlR-WvwlpdEM-0BTZ4kgNV2GXyNbX0Jed_kVPcjgddsEJv5So_sGrDMHXNn_6w3MZABdq2-l7hwQPJmqrxKrRn0lLW-cEEGloPUgLeKJTODHiEwC9uMl4gBQQ4MaGHrMXewJfBkNhJtN0wWA-2aUY3NekGkeBtohRFyPMp15xSWEAsK_2QZewlMAkxZmrBL4sGIN4uYQhQj7OVDUuCFQNib-Xp7Q3lQ7qpTdbDYKt1M_nbsZoarha3nu9tkUPtJi0Mph0673LvdgjnWlhI5AhMuHQLcO5YNu0q7q6eyf1Hx7njp0JuxDR_VnV6XLWDCg6Yz-unz4OigIoF02BDrW6VEjS5s84hxwJMuBcK5Q0amFrpzuakFBUgVRpU",
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.7437264,
                    "lng": -90.3127765
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.7424095701072778,
                        "lng": -90.31142382010728
                    },
                    "southwest": {
                        "lat": -0.7451092298927222,
                        "lng": -90.31412347989273
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "La Isla Hotel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2304,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/108329480289903789944\">Josh Johnson</a>"
                    ],
                    "photo_reference": "ATtYBwKLupm5PUBRDruzJie84YKx7FXem-lGDTJrF7jiXZFjsbjyXgf2w_pS5LuVgwwcF3SApmtnyslI_tmjm1SErGuE3-xrgt3dwjiJ35BQ6r6NM4BFOR7w2MdAfXQvP9MMNlCa7ULFzTPXI3tf_mS-x_9RFuRSeS-tQb5jS_JHZFLt-lvU",
                    "width": 4608
                }
            ],
            "place_id": "ChIJl1r8x13vqpoRLl8oIwBxEkI",
            "plus_code": {
                "compound_code": "7M4P+GV Puerto Ayora, Ecuador",
                "global_code": "66FF7M4P+GV"
            },
            "rating": 4.7,
            "reference": "ChIJl1r8x13vqpoRLl8oIwBxEkI",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 47,
            "vicinity": "Indefatigable 072 and Charles Darwin, Ave Santa Cruz"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.7470129,
                    "lng": -90.3144196
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.7456770701072778,
                        "lng": -90.31303567010727
                    },
                    "southwest": {
                        "lat": -0.7483767298927222,
                        "lng": -90.31573532989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Ikala",
            "photos": [
                {
                    "height": 3000,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/111011427543875515180\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwIpRZ9UX-aEbIFHbXPqNBX6BjLyMdifrI8hNHNEiNscpsCkTb3uKDUUNXH6j1ck472wSl03ULBPYmGVim7VDUosTzdU2b8uplZqvp-q7u4y_Ce_oQGBqyTcw2mvdJwtPrA3jlz1LenkgBzUC7mCl0JzJov1aSIWY-4nIqEjl52YW7mu",
                    "width": 4000
                }
            ],
            "place_id": "ChIJZ26qYi1dqpoRj8aSBqTto20",
            "plus_code": {
                "compound_code": "7M3P+56 Puerto Ayora, Ecuador",
                "global_code": "66FF7M3P+56"
            },
            "rating": 4.5,
            "reference": "ChIJZ26qYi1dqpoRj8aSBqTto20",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 27,
            "vicinity": "Thomas de Berlanga 110 y, Puerto Ayora"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.7507153999999999,
                    "lng": -90.30968
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.7493655701072776,
                        "lng": -90.30833017010728
                    },
                    "southwest": {
                        "lat": -0.7520652298927221,
                        "lng": -90.31102982989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Angermeyer Waterfront Inn",
            "photos": [
                {
                    "height": 2992,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/107302279571564802159\">Young Lee</a>"
                    ],
                    "photo_reference": "ATtYBwKuMqcxxYSxCKxsdgTRN7qsgz3PLRSQjeYZBGw4fkyhfdQ0hX7zy5niB4MaobNAydQ8WpZgkmCE7_TPu8BBOpBHr8GVQgNZijOSOo4M69YShDsuxD-vlHkX0MjZBK_GazJsSDZ7DUYDzBKpK_1FBatRuEpG8LRmtMpFM8_03WDFzZAw",
                    "width": 4000
                }
            ],
            "place_id": "ChIJ2bV0nE1dqpoR9fBlkBjWT1E",
            "plus_code": {
                "compound_code": "6MXR+P4 Puerto Ayora, Ecuador",
                "global_code": "66FF6MXR+P4"
            },
            "rating": 4.5,
            "reference": "ChIJ2bV0nE1dqpoR9fBlkBjWT1E",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 246,
            "vicinity": "Barrio Punta Estrada, Puerto Ayora"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.742543,
                    "lng": -90.309953
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.7411203201072777,
                        "lng": -90.30860002010728
                    },
                    "southwest": {
                        "lat": -0.7438199798927222,
                        "lng": -90.31129967989273
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Galapagos Habitat by Eco Luxury Group",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3024,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/108248532828651469905\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwLAcxtYGZkMWuyWVTAXy1nMuRJqH9UjSleYmbmNa28mKO4PGwz17mg37lVk0YcRELjAxXdf-hGtQHIPyPhtvqxuJbIJuwrmkOdPwMJkWxD8VEvQDNQxOOa6y9g_tmcOxaaUY55ATwtV0wTLRPPRSqRcIZdEZSvmetdtpp9e_fIbT8Tn",
                    "width": 4032
                }
            ],
            "place_id": "ChIJeeVlP0VdqpoRDsUoQtJxiSo",
            "plus_code": {
                "compound_code": "7M4R+X2 Puerto Ayora, Ecuador",
                "global_code": "66FF7M4R+X2"
            },
            "rating": 4.5,
            "reference": "ChIJeeVlP0VdqpoRDsUoQtJxiSo",
            "scope": "GOOGLE",
            "types": [
                "travel_agency",
                "lodging",
                "restaurant",
                "food",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 202,
            "vicinity": "Ave Charles Darwin, Puerto Ayora"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.7424864,
                    "lng": -90.312699
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.7411434701072777,
                        "lng": -90.31134342010728
                    },
                    "southwest": {
                        "lat": -0.7438431298927222,
                        "lng": -90.31404307989273
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Acacia Galapagos Boutique Hotel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 4016,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/117840347475879240894\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwKnupVMoMnLBI2rJqOtGtwWw17BBIbYwafULIWkjwjGRW8b4h4hzZSBlSAtUOl-aBwWKUTdT0y3A6ket6DGtdwNsQapheWF8HHjdcBpnYmxSY033gx4mu2NCAGaxdab624Ao2PLCU5s1MYC3qL-kNRGYesjUbGxc5mdobk_bH5WC6c",
                    "width": 6016
                }
            ],
            "place_id": "ChIJh_nefHldqpoRND6wtvF3SSo",
            "plus_code": {
                "compound_code": "7M5P+2W Puerto Ayora, Ecuador",
                "global_code": "66FF7M5P+2W"
            },
            "rating": 4.5,
            "reference": "ChIJh_nefHldqpoRND6wtvF3SSo",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 12,
            "vicinity": "C/ Floreana Y Matazarnos, Puerto Ayora"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.7533386999999999,
                    "lng": -90.3116
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.7519888701072777,
                        "lng": -90.31025017010728
                    },
                    "southwest": {
                        "lat": -0.7546885298927222,
                        "lng": -90.31294982989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Finch Bay Galapagos Hotel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 5301,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/113893946987405742149\">Finch Bay Eco Hotel</a>"
                    ],
                    "photo_reference": "ATtYBwIoSWcryIKIUOz2BcjM_41o_9qkKCliEbT3URj7UQWRp8GlCxs_kY-zkm8HFsRoq0INbRHoxu7DU0bFZTjT5PBnNpLtp93fUaCArphs_zXlPF0t5mNXiXx-R1uzgVVP-PHmNEe6rMmkuxWk5STYVfsXR35LJs3IFhHs1vf8SaO6Ia3s",
                    "width": 7951
                }
            ],
            "place_id": "ChIJRxLey05dqpoRMOAGLSZsesc",
            "plus_code": {
                "compound_code": "6MWQ+M9 Puerto Ayora, Ecuador",
                "global_code": "66FF6MWQ+M9"
            },
            "rating": 4.7,
            "reference": "ChIJRxLey05dqpoRMOAGLSZsesc",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 201,
            "vicinity": "Barrio Punta Estrada, Puerto Ayora"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.745699,
                    "lng": -90.31147999999999
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.7442615701072778,
                        "lng": -90.31023837010727
                    },
                    "southwest": {
                        "lat": -0.7469612298927222,
                        "lng": -90.31293802989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Grand Hotel Leon Marino Galapagos",
            "place_id": "ChIJh5P_Bk9dqpoRbfn2zm2mzWY",
            "plus_code": {
                "compound_code": "7M3Q+PC Puerto Ayora, Ecuador",
                "global_code": "66FF7M3Q+PC"
            },
            "rating": 5,
            "reference": "ChIJh5P_Bk9dqpoRbfn2zm2mzWY",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 2,
            "vicinity": "Ave Charles Darwin, Puerto Ayora"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.7389388000000001,
                    "lng": -90.30928019999999
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.737531920107278,
                        "lng": -90.30796282010728
                    },
                    "southwest": {
                        "lat": -0.7402315798927224,
                        "lng": -90.31066247989273
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "La Fortaleza de Haro",
            "photos": [
                {
                    "height": 2448,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/113378372014429135841\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwLM2PNZ2-stc-a4gDvptCPPSekAT1f0iA3vyI1xr8A8Bf-gdL8-JPk7_3_-BGX2RKrbpujhjIFL41gGx9vhnojIUx1TWK6H_8OnWCR0cJH3Xu3jWjdbKvdEDRjfA9Hmyv3vF2q98C-7WyiXM8qOd6QkdF6gLEXFKELNWwfwwUK8lZuO",
                    "width": 3264
                }
            ],
            "place_id": "ChIJWyp1VkNdqpoRJi7q_vrZY04",
            "plus_code": {
                "compound_code": "7M6R+C7 Puerto Ayora, Ecuador",
                "global_code": "66FF7M6R+C7"
            },
            "rating": 4.6,
            "reference": "ChIJWyp1VkNdqpoRJi7q_vrZY04",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 30,
            "vicinity": "Petrel, Puerto Ayora"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.7426174999999999,
                    "lng": -90.3110695
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.7413148201072777,
                        "lng": -90.30970427010728
                    },
                    "southwest": {
                        "lat": -0.7440144798927222,
                        "lng": -90.31240392989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hotel Silberstein",
            "photos": [
                {
                    "height": 664,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/101265017020662515273\">ruddy karundeng</a>"
                    ],
                    "photo_reference": "ATtYBwLqhAs0owpuir1ZqGUixvHUlbgpaw0l4vtlDRNTCAhgUWaAKo3UzF-q4_EHa9R4muhxN6XobjDLSRNSNlByuJbNa0wVijXaakXqIuRsi7bzgBnC8SyR1mT_xG6IQCfqc-rSEgP-7zQqN2vhXu6D4DLuCDBN4EiiDRYVpEDhuEtwOjLc",
                    "width": 1000
                }
            ],
            "place_id": "ChIJO1CrSEpdqpoRW-q0rBGhnIQ",
            "plus_code": {
                "compound_code": "7M4Q+XH Puerto Ayora, Ecuador",
                "global_code": "66FF7M4Q+XH"
            },
            "rating": 4.1,
            "reference": "ChIJO1CrSEpdqpoRW-q0rBGhnIQ",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 142,
            "vicinity": "Av. Charles Darwin y Piqueros, Puerto Ayora"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.7434337999999999,
                    "lng": -90.3134537
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.7420880701072777,
                        "lng": -90.31205632010727
                    },
                    "southwest": {
                        "lat": -0.7447877298927221,
                        "lng": -90.31475597989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Mainao",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 1501,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/106962798856612867337\">Mainao</a>"
                    ],
                    "photo_reference": "ATtYBwK9h-GZbfbcWPhyZO4BI28bI2myR2Wu1ycK_rmnQ2LuBwV3wJEyWMrHwJDTIfQzNjz1MTJ0hKD4boIKCng5DCfscwUxUHWsaNivUn7qusT3QEkjuOW-l2v0Jwg6ZHpvNPyB1G6dVZJHZqTaUJFT-VzNStds5G8xJTKzdhYYdg4u1tg4",
                    "width": 2048
                }
            ],
            "place_id": "ChIJURYY_EVdqpoR1AvYdCNKMTg",
            "plus_code": {
                "compound_code": "7M4P+JJ Puerto Ayora, Ecuador",
                "global_code": "66FF7M4P+JJ"
            },
            "rating": 4.2,
            "reference": "ChIJURYY_EVdqpoR1AvYdCNKMTg",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 69,
            "vicinity": "Puerto Ayora"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -0.7073553,
                    "lng": -90.3166277
                },
                "viewport": {
                    "northeast": {
                        "lat": -0.7058936201072776,
                        "lng": -90.31541952010727
                    },
                    "southwest": {
                        "lat": -0.7085932798927221,
                        "lng": -90.31811917989272
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Bay House",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 853,
                    "html_attributions": [

{
    "html_attributions": [],
    "next_page_token": "ATtYBwLy9hTzgrZgAzijZmOuKvjZf6c--Ah6UghDkWyMfpPcefp182gOC3xviEayBXRHwoVOPzwTwcgPKJz1Dhz8dwMMt2hQCYZrYAaPRCLLd8pZNpfXl2xUUTZMX4V33nLQ2cS2CKmMIVC7KXiYippDRSYUo44w2uZzgZfOE8ogYFLZgtp7oFLGSFTFmic-bB3crm0ZhC2_E6KCj3hDKE7cWFdkYu7WrGWcQC69aaf8OiA6--17rUIa1zcxKmxYTbR3Eo69-_Cxh3pvBUYrk9vi5zhrENcyk1DHeCi-Y1asMLj6T2wRQwJZWz7hJqdmaW25CMDK2vqLibpRHjX7ytkZPjgJRKwRad2Z2FTcmFnzoN96sLVgxhnzy3HzpzFdXTmWIgbTnPMJblGCWYbisBJAjD74BNuxV5X_BNfjXfxE-BSP8rpC3V3UkMaYD2_E3gQ",
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -3.8011121,
                    "lng": 102.2749441
                },
                "viewport": {
                    "northeast": {
                        "lat": -3.799762270107279,
                        "lng": 102.2762939298927
                    },
                    "southwest": {
                        "lat": -3.802461929892722,
                        "lng": 102.2735942701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Mercure Bengkulu",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 4480,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/112384546653595201388\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwLf6pkrbfaCTPkUeKhmUccdH-FSvQluTuX3iwy8ymN39dxYfdt5ovui4doIzhQhn8YsCINk-pub2quTOILpF3eCdwann2JVzN8pf5Lo19mZqywdX4ubBkn3bSY4c-FqJUHJz5GqYfV1oYCZRjoagzzUwKuhFGaQq5w1VN7BpG6uwL82",
                    "width": 6720
                }
            ],
            "place_id": "ChIJQzRkihSwNi4Rqb76obUbZBs",
            "plus_code": {
                "compound_code": "57XF+HX Padang Jati, Bengkulu City, Bengkulu, Indonesia",
                "global_code": "6P8457XF+HX"
            },
            "rating": 4.4,
            "reference": "ChIJQzRkihSwNi4Rqb76obUbZBs",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 705,
            "vicinity": "Jl. S. Parman No.27, Padang Jati, Kota Bengkulu"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -3.792276,
                    "lng": 102.2610819
                },
                "viewport": {
                    "northeast": {
                        "lat": -3.791046820107279,
                        "lng": 102.2624285298927
                    },
                    "southwest": {
                        "lat": -3.793746479892723,
                        "lng": 102.2597288701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Splash Hotel Bengkulu",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2268,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/102328575586564711570\">aris purnama</a>"
                    ],
                    "photo_reference": "ATtYBwKSGGD0y7ZOeVJ6hCLP6YcKXCgMR1ziQ_zi0aKucnnP5J68O1P8FHlToeZC-SqNEfw1fCNozMaS1-rYntQrLh5PdIIBsIZLHGdM0vOwnvQ11So_f-FlDze7E-gD7XvJ_M4ujDhndnos07z3YvKmEMrUTL7DypZSgSsv5hkauHb062DW",
                    "width": 4032
                }
            ],
            "place_id": "ChIJK9jeBiSwNi4RehPymI8qcjc",
            "plus_code": {
                "compound_code": "6756+3C Tengah Padang, Bengkulu City, Bengkulu, Indonesia",
                "global_code": "6P846756+3C"
            },
            "rating": 4,
            "reference": "ChIJK9jeBiSwNi4RehPymI8qcjc",
            "scope": "GOOGLE",
            "types": [
                "night_club",
                "lodging",
                "bar",
                "restaurant",
                "food",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 984,
            "vicinity": "Jl. Jendral. Sudirman No.48, Tengah Padang, Kota Bengkulu"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -3.7978888,
                    "lng": 102.2729506
                },
                "viewport": {
                    "northeast": {
                        "lat": -3.796524920107279,
                        "lng": 102.2741975798927
                    },
                    "southwest": {
                        "lat": -3.799224579892722,
                        "lng": 102.2714979201073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hotel Santika Bengkulu",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3491,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/112358647589698850684\">HOTEL SANTIKA BENGKULU</a>"
                    ],
                    "photo_reference": "ATtYBwKiw3zzAu19Pj4FZ6ENGg1xULP569WgA2Gpwb3mSQjGA_PXVI6hLhw4lq3S89KLSmdK7nuCFNPGLNDAJtmWyniOtqiesmevc-legprGaBse3rnUVEn-ZzR7fZulqstIFgzVCKtvXh7cw_b_Tj0-5BruXuT-qaMgxoT0JNYIon2Gs__T",
                    "width": 3822
                }
            ],
            "place_id": "ChIJ1_fq-RWwNi4RPVCH8tynUzk",
            "plus_code": {
                "compound_code": "672F+R5 Sawah Lebar, Bengkulu City, Bengkulu, Indonesia",
                "global_code": "6P84672F+R5"
            },
            "rating": 4.4,
            "reference": "ChIJ1_fq-RWwNi4RPVCH8tynUzk",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 2560,
            "vicinity": "Jl. Jati No.45, Sawah Lebar, Kota Bengkulu"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -3.810468,
                    "lng": 102.284939
                },
                "viewport": {
                    "northeast": {
                        "lat": -3.809045020107278,
                        "lng": 102.2863481798927
                    },
                    "southwest": {
                        "lat": -3.811744679892722,
                        "lng": 102.2836485201073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hotel Tanjung Karang",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2048,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/114412201744776794626\">Tanjung Karang Hotel and Restaurant</a>"
                    ],
                    "photo_reference": "ATtYBwK8VVaZ0oREfsiAcMhCZf7tXFaYcO6D1ROlh7HGqbc1v4BdLRX3fYRcY6NTGWQCsMFylzXAA2Z98hNBdr0evgNdxZzjf7bDnW46l6i4shtYnRwSbqKLekW-eJxi6pHH5oneYlaPVeV9JoVQJGaUVICZtHu3TAlap_9ttzg05U-ttKuA",
                    "width": 2048
                }
            ],
            "place_id": "ChIJz2CELnGwNi4RVthxKyfZrqo",
            "plus_code": {
                "compound_code": "57QM+RX Tanah Patah, Bengkulu City, Bengkulu, Indonesia",
                "global_code": "6P8457QM+RX"
            },
            "rating": 4.2,
            "reference": "ChIJz2CELnGwNi4RVthxKyfZrqo",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 492,
            "vicinity": "Jl. Mayjen Sutoyo No.4, Tanah Patah, Kota Bengkulu"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -3.8093588,
                    "lng": 102.2677012
                },
                "viewport": {
                    "northeast": {
                        "lat": -3.807942470107277,
                        "lng": 102.2691757798927
                    },
                    "southwest": {
                        "lat": -3.810642129892721,
                        "lng": 102.2664761201073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Amaris Hotel Bengkulu",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2250,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/115094775125708951659\">Deny Cahya</a>"
                    ],
                    "photo_reference": "ATtYBwLbApduf50WBT8Y9MiJbOlCNMUiSSas1CMb0muj5vyIaCpDs_yqEpTtyCBrhJqt8f6Np7O5vXwI3kAHS0c6_GYOn-ZlASml24uRj8iKBuKLZmc57WiTdW6dCWh9iwA98yhDil0mOYm4cZmeZPEVC2JiKsIex4dmLHXKlJKv07rd8TfX",
                    "width": 4000
                }
            ],
            "place_id": "ChIJ5_wpvQ-wNi4RQk9ppCIXzJg",
            "plus_code": {
                "compound_code": "57R9+73 Penurunan, Bengkulu City, Bengkulu, Indonesia",
                "global_code": "6P8457R9+73"
            },
            "rating": 4.1,
            "reference": "ChIJ5_wpvQ-wNi4RQk9ppCIXzJg",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 1492,
            "vicinity": "Jl. Putri Gading Cempaka No.8, RT.14/RW.01, Penurunan, Kota Bengkulu"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -3.7963968,
                    "lng": 102.2653681
                },
                "viewport": {
                    "northeast": {
                        "lat": -3.795111570107278,
                        "lng": 102.2666013298927
                    },
                    "southwest": {
                        "lat": -3.797811229892722,
                        "lng": 102.2639016701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Sinar Sport Hotel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3744,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/107024911637626283566\">Sinar Sport Hotel</a>"
                    ],
                    "photo_reference": "ATtYBwLzv_2SnHhbELMptMEzv-T1E-ZlF6oqYSuNrJ5CON6uh9JaE-CxnQuTQMuv68v_hHc7_EB5ljSBvAoBxfMI5HnF4qua0Ki7AP9oAGJ5DwXjiL50psn6qMpAF3mnLJFw0nYj9sh7qZkcjyg9byBmABVzMIe2YRg3lX7Jyw7mVKLuczlM",
                    "width": 5616
                }
            ],
            "place_id": "ChIJS_Z76SKwNi4RXkvFp01L3Jw",
            "plus_code": {
                "compound_code": "6738+C4 Anggut Dalam, Bengkulu City, Bengkulu, Indonesia",
                "global_code": "6P846738+C4"
            },
            "rating": 4.3,
            "reference": "ChIJS_Z76SKwNi4RXkvFp01L3Jw",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 1662,
            "vicinity": "Jl. Letjend Suprapto No.378, Anggut Dalam, Kota Bengkulu"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -3.8375145,
                    "lng": 102.3051962
                },
                "viewport": {
                    "northeast": {
                        "lat": -3.836104520107279,
                        "lng": 102.3064721298927
                    },
                    "southwest": {
                        "lat": -3.838804179892723,
                        "lng": 102.3037724701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "The Madeline Hotel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3936,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/115800558478916596071\">Dimas Kurniawan</a>"
                    ],
                    "photo_reference": "ATtYBwKONMwrsTcbCDPozAF6bYzsa-i-Jn7Oh9mYVSo-8cz06u-83Nkqu9RDP3nMZ_6baqhEcZlWWzQu75fD8qR9wj3R5BjMGeiKiHhwBELHwxpKdFes4Ht44WY9fbS9LxW94Ry9kgdfsIKHV8Z1sH6mHwiDE4DOVThhINodgJ10jJio2iT1",
                    "width": 5248
                }
            ],
            "place_id": "ChIJH2SSOmC6Ni4RMlpQTsjvBE0",
            "plus_code": {
                "compound_code": "5864+X3 Lingkar Barat, Bengkulu City, Bengkulu, Indonesia",
                "global_code": "6P845864+X3"
            },
            "rating": 4.2,
            "reference": "ChIJH2SSOmC6Ni4RMlpQTsjvBE0",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 997,
            "vicinity": "Jl. Bakti Husada No.88, Lkr. Barat, Kota Bengkulu"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -3.824945,
                    "lng": 102.2789058
                },
                "viewport": {
                    "northeast": {
                        "lat": -3.823503720107278,
                        "lng": 102.2801781798927
                    },
                    "southwest": {
                        "lat": -3.826203379892722,
                        "lng": 102.2774785201073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Pinus Hotel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3000,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/117461441708494332679\">Rosika Darmawan</a>"
                    ],
                    "photo_reference": "ATtYBwJ0Pw5DUTMoM_xmbrwMcpmbD4XQWgs51A84Wa8AAqP30_NxgMDx0Jn0ra1C-U0uNCjc4BU1Jk1y3y4kqDG8yiNZr9sDg4kLJQ3VtzukZjy8DaU-H3v3AP9UhDkPBTfUZRpMolb4ctsh79jDwiy9YHyjP7EJLEw_t6fvvX4xRR2D9C16",
                    "width": 4000
                }
            ],
            "place_id": "ChIJ2zXVBte7Ni4RWeo9NG-pQkc",
            "plus_code": {
                "compound_code": "57GH+2H Lempuing, Bengkulu City, Bengkulu, Indonesia",
                "global_code": "6P8457GH+2H"
            },
            "rating": 4.4,
            "reference": "ChIJ2zXVBte7Ni4RWeo9NG-pQkc",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 13,
            "vicinity": "Lempuing, Bengkulu City"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -3.7593292,
                    "lng": 102.2771432
                },
                "viewport": {
                    "northeast": {
                        "lat": -3.758186720107278,
                        "lng": 102.2783460298927
                    },
                    "southwest": {
                        "lat": -3.760886379892721,
                        "lng": 102.2756463701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "DJo Front One Inn Hotel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 726,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/100238916374836783057\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwL1nwA5b7wljbcKu6TwDaAORniRd_AATVw7i3vbUuHsXXntVBQmOjUQdvlnOQ58dF8cHhxwy1xpgI3tbaoIGCKTRcWeu4ZPzVreFJ7JPM15qMCTn8yG6VIPQ89YT4IxoZVy3v5ThAtgoU4FQhwTDkA7mIXREG9c1J8SpamwNfWqgeIH",
                    "width": 714
                }
            ],
            "place_id": "ChIJDfTCcMCxNi4RIk91oeRLfws",
            "plus_code": {
                "compound_code": "67RG+7V Kandang Limun, Bengkulu City, Bengkulu, Indonesia",
                "global_code": "6P8467RG+7V"
            },
            "rating": 4.1,
            "reference": "ChIJDfTCcMCxNi4RIk91oeRLfws",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 313,
            "vicinity": "Jl. WR. Supratman No.8, Kandang Limun, Kota Bengkulu"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -3.7999907,
                    "lng": 102.2648529
                },
                "viewport": {
                    "northeast": {
                        "lat": -3.798664020107278,
                        "lng": 102.2662648298927
                    },
                    "southwest": {
                        "lat": -3.801363679892722,
                        "lng": 102.2635651701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Dena Hotel",
            "photos": [
                {
                    "height": 1536,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/106792036982836931054\">Jiiu Anakaneh</a>"
                    ],
                    "photo_reference": "ATtYBwL8q02AlcGdd1QU-aOBZjy-UeFtYtgXUHhYcD02haTS7ni9TymS26svyFf8J-gb4w8KbGgRor52_PbhJkSEqMeqmpfyHJxQkRTKs1fzTRt8r7bVj7vBwLMm9RI1qGX0G26i9f2OW1wcxV_zeo9r5zoZgNU3QYja5nHNNNYPi6iwuYF6",
                    "width": 2048
                }
            ],
            "place_id": "ChIJofe2x2G5Ni4R7JaRazk27dI",
            "plus_code": {
                "compound_code": "6727+2W Penurunan, Bengkulu City, Bengkulu, Indonesia",
                "global_code": "6P846727+2W"
            },
            "rating": 4.1,
            "reference": "ChIJofe2x2G5Ni4R7JaRazk27dI",
            "scope": "GOOGLE",
            "types": [

{
    "html_attributions": [],
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 8.5379589,
                    "lng": 78.1173417
                },
                "viewport": {
                    "northeast": {
                        "lat": 8.53930582989272,
                        "lng": 78.11876862989271
                    },
                    "southwest": {
                        "lat": 8.536606170107277,
                        "lng": 78.11606897010726
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "PEARL GARDEN RESORT",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3472,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/101613293518518363207\">Ihsaan Muhiyadheen</a>"
                    ],
                    "photo_reference": "ATtYBwLLF4__CiyOson9_00q07t0DPnjdU6yy6vw49p0tO7RzPlWL7b00To6PQDwxVKEHQvWYBVHdAMwIiasYrjqEevwKJ-MzrCbSuWNJf73yKkPpOzrFCf2gHX5iqqnIr3Q2OHGXGGWdqYhb-B5yQxxWid504yfqi7KkykfhelqYq87CP32",
                    "width": 4624
                }
            ],
            "place_id": "ChIJCeMzTVaRAzsRfJJH-VOrHcA",
            "plus_code": {
                "compound_code": "G4Q8+5W Veerapandianpattinam, Tamil Nadu, India",
                "global_code": "6JWWG4Q8+5W"
            },
            "rating": 4.3,
            "reference": "ChIJCeMzTVaRAzsRfJJH-VOrHcA",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 54,
            "vicinity": "Thoothukudi-Tiruchendur Rd, Veerapandianpattinam"
        }
    ],
    "status": "OK"
}
{
    "html_attributions": [],
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.2038809,
                    "lng": -159.7547646
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.20266042010728,
                        "lng": -159.7535242701072
                    },
                    "southwest": {
                        "lat": -21.20536007989272,
                        "lng": -159.7562239298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Club Raro Resort",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3629,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/105679576607651357970\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwLlTUtsr-M1bJQaMG_yrqhjFyMLxtSsN1ZJxrjGXUb2ED3w3PW4lnltF71xEmeYVaytAYxZofWiY_ukdWlsDYhyHia2DmUBAj9HiDY1SMM9hi0XCHhQfxJOcXvfgzZ42BxOA580FeZRl9IyiHW-adKdmIM1yMhWzbT_k45E_nsINAVE",
                    "width": 5444
                }
            ],
            "place_id": "ChIJ1zZCmbbRV3ERxrdPE8eKN1k",
            "plus_code": {
                "compound_code": "Q6WW+C3 Avarua District, Cook Islands",
                "global_code": "53C2Q6WW+C3"
            },
            "rating": 3.8,
            "reference": "ChIJ1zZCmbbRV3ERxrdPE8eKN1k",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 116,
            "vicinity": "Rarotonga"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.239665,
                    "lng": -159.7276552
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.23840867010728,
                        "lng": -159.7269336201073
                    },
                    "southwest": {
                        "lat": -21.24110832989272,
                        "lng": -159.7296332798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Sunrise Beach Bungalows",
            "photos": [
                {
                    "height": 3456,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/117588244611154963182\">Michelle Day-Lewis</a>"
                    ],
                    "photo_reference": "ATtYBwLkwJ-aOpnN95cROZDoz25aFsAG4x29XtrdxeopMyoBDKNm-LmlbFP_qs9Lt1o-qv0rkITxYY5qZKp3mKsTjlqU5NoMA-Ynwm0klmwYqfHWK6GUrLBToAQ2UpYAK0JAy-dUNM7i-eNQu_lni84YDuAENnUyPh3UAzH6IguKkkinQIvu",
                    "width": 4608
                }
            ],
            "place_id": "ChIJPRmNQJfTV3ERv4InVhQQ7Kk",
            "plus_code": {
                "compound_code": "Q76C+4W Ngatangiia District, Cook Islands",
                "global_code": "53C2Q76C+4W"
            },
            "rating": 3.7,
            "reference": "ChIJPRmNQJfTV3ERv4InVhQQ7Kk",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 21,
            "vicinity": "Main Road Turangi, Muri Beach"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.2333391,
                    "lng": -159.7303007
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.23199412010728,
                        "lng": -159.7291001701073
                    },
                    "southwest": {
                        "lat": -21.23469377989272,
                        "lng": -159.7317998298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Ocean Escape Resort & Spa",
            "photos": [
                {
                    "height": 4032,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/118352365705092553774\">Sophie Clunie</a>"
                    ],
                    "photo_reference": "ATtYBwIR1fbb4Qur0XAO5YYVVUWceEnuzwjaq-eB5l5Cmy7x-JJQCWWbvRpkfP9ft6ErLgM7MUN1kB2qTg_TQZSsnMIC2RGCjKD2ilSxdqjfcPXznP1Hi_JzrzEqfz6_2RiNRWO4FAQNx1xk5gE66lmaqKbD2F9O1CD7p0B4tGUuUNNKlu5A",
                    "width": 3024
                }
            ],
            "place_id": "ChIJeYURFb3TV3ERuG7_o5Bd-kc",
            "plus_code": {
                "compound_code": "Q789+MV Arorangi District, Cook Islands",
                "global_code": "53C2Q789+MV"
            },
            "rating": 4.5,
            "reference": "ChIJeYURFb3TV3ERuG7_o5Bd-kc",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 2,
            "vicinity": "Ara Tapu, Arorangi District"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.2077672,
                    "lng": -159.7910155
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.20632227010728,
                        "lng": -159.7897568701073
                    },
                    "southwest": {
                        "lat": -21.20902192989272,
                        "lng": -159.7924565298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Kia Orana Villas and Spa",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3070,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/117241055935526110065\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJvDY_giWKKDp9B20Un79HXrwU3lINBiSWReEHetQmsW1qZH6CM6AHA44JXtiGnuWoGxeFXCdhOrWKVTxQpF-eUoJnD678q97ZJcufCUQqgRtBnRWZiuh19InLZMjCIvv4u7Ntp2MwykwhaJEkWAuw7-59Olwt-YdiJKEpK84TNrnJJ",
                    "width": 5464
                }
            ],
            "place_id": "ChIJsd6fJr3RV3ERUODeRvIwEKg",
            "plus_code": {
                "compound_code": "Q6R5+VH Avarua District, Cook Islands",
                "global_code": "53C2Q6R5+VH"
            },
            "rating": 4.8,
            "reference": "ChIJsd6fJr3RV3ERUODeRvIwEKg",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 15,
            "vicinity": "2 Pa Ariki Rd, Rarotonga"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.1991091,
                    "lng": -159.7953621
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.19791042010727,
                        "lng": -159.7940290201073
                    },
                    "southwest": {
                        "lat": -21.20061007989272,
                        "lng": -159.7967286798927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "The Islander Hotel",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 770,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/116182363482589837891\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJ4_JBt_ddNVM664HOYNJb4s9hpixm6inFYxzzL7B_nwRyDO2BbtQNYqWs5HqMabtmLWP775049vkXBiTQJT1vLVlNOPsJgwQHThkbXrF_ssez0Us3hfSn9_Jh2nBsoaRYhzq5pS-8hT1uTaBK5xO_hXvwe9VkYfH3ioKMEAfvwvP5O",
                    "width": 1368
                }
            ],
            "place_id": "ChIJmVoxwbjRV3ERXkJfFo6QLjY",
            "plus_code": {
                "compound_code": "R623+9V Avarua District, Cook Islands",
                "global_code": "53C2R623+9V"
            },
            "rating": 4,
            "reference": "ChIJmVoxwbjRV3ERXkJfFo6QLjY",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 109,
            "vicinity": "Ara Tapu Avarua District"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.204566,
                    "lng": -159.7522
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.20332852010728,
                        "lng": -159.7509067701073
                    },
                    "southwest": {
                        "lat": -21.20602817989272,
                        "lng": -159.7536064298928
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Kiikii Inn & Suites - Rarotonga",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 1536,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/100680853646633201105\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJv40GZX2Mfslh1MhFglvuGC2EZM3SdKJGVeTiMntu0lpbKiEd1ArNYen5416xAfuZuk9AxHMYdVAfgqxgBd4MXQJxXFmOfXLCiTyfEozHLyo5cZONcuK-edS901t3FFsAgcJDh-VzBAbYs5q4IKaTGCyjISKiVznW4h5lenpF07zq4",
                    "width": 2730
                }
            ],
            "place_id": "ChIJJ-8mSbrTV3ERWSX_ApWf-uA",
            "plus_code": {
                "compound_code": "Q6WX+54 Avarua District, Cook Islands",
                "global_code": "53C2Q6WX+54"
            },
            "rating": 3.3,
            "reference": "ChIJJ-8mSbrTV3ERWSX_ApWf-uA",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 13,
            "vicinity": "Rarotonga"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.2492482,
                    "lng": -159.7309716
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.24786447010728,
                        "lng": -159.7296165701073
                    },
                    "southwest": {
                        "lat": -21.25056412989272,
                        "lng": -159.7323162298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
            "name": "Muri Lagoon View Bungalows",
            "opening_hours": {},
            "photos": [
                {
                    "height": 3024,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/116372165337357030191\">vikas raj bhagat</a>"
                    ],
                    "photo_reference": "ATtYBwJSF1PNwrYSUXQOngSlEDW45FnQXigtBbVExR14_cNBRVjC77qwfMakll5GUnTkpAHYCQFWqV7fC0A773X1dZAJHNTKlGYktqANt7QoaxLxdGR7AVPiW-6s2DGUumWsxNGaXEB4oGwuWVJLZEpH-xeFoozB3Lr7zMcva1tTMeMuuxSL",
                    "width": 4032
                }
            ],
            "place_id": "ChIJWWflB4_TV3EReXFC4y06mME",
            "plus_code": {
                "compound_code": "Q729+8J Ngatangiia District, Cook Islands",
                "global_code": "53C2Q729+8J"
            },
            "rating": 4.8,
            "reference": "ChIJWWflB4_TV3EReXFC4y06mME",
            "scope": "GOOGLE",
            "types": [
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 4,
            "vicinity": "Aroko Drive, Rarotonga"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.2526919,
                    "lng": -159.729495
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.25126782010728,
                        "lng": -159.7285834701073
                    },
                    "southwest": {
                        "lat": -21.25396747989272,
                        "lng": -159.7312831298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Manea on Muri",
            "photos": [
                {
                    "height": 4000,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/108557537483619848461\">Chris Doms</a>"
                    ],
                    "photo_reference": "ATtYBwJCsBryvv6d-IQhwTUccidr_FWi4IM_HLDR0kGMtaBMmHIkGrb4q8CakFcxFdMkli__yrDy3BHqRPuKlsoaUhbu7VKx_81xhDiYv7CiDYIDV28eM-FlaY5dCDCMNjtGV0p7ONOyDn0eOy81T929WegQYq5wi5myC9NegR3nZ3aAtA8P",
                    "width": 6000
                }
            ],
            "place_id": "ChIJF2V2s4jTV3ERrAl-RxWKEdE",
            "plus_code": {
                "compound_code": "P7WC+W6 Ngatangiia District, Cook Islands",
                "global_code": "53C2P7WC+W6"
            },
            "rating": 3.9,
            "reference": "ChIJF2V2s4jTV3ERrAl-RxWKEdE",
            "scope": "GOOGLE",
            "types": [
                "tourist_attraction",
                "natural_feature",
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 27,
            "vicinity": "RarotongaAre Tapu Muri Beach"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.2538378,
                    "lng": -159.7288215
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.25290882010728,
                        "lng": -159.7278253701072
                    },
                    "southwest": {
                        "lat": -21.25560847989273,
                        "lng": -159.7305250298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Muri Beach Villa",
            "photos": [
                {
                    "height": 1600,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/112443035990572214562\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwLcqTDV4SMCEUY0vTXvpsOy6gk0YSkRcy8G5_8OKwmvkkq_8g96-T0WCE0uiRfxJsorJmxFd5AwUWEeiPvLQVMWbI4eymjrdIB-HwiNsdUkb9HfUG8xIvKNIXmNE7aPdMH-ZtbuprUtgyQKTCosQPQ3uJCvVX5I7kj9R6t02rdIsAU7",
                    "width": 2400
                }
            ],
            "place_id": "ChIJK-TATc7TV3ERvoG855SN0z8",
            "plus_code": {
                "compound_code": "P7WC+FF Ngatangiia District, Cook Islands",
                "global_code": "53C2P7WC+FF"
            },
            "rating": 5,
            "reference": "ChIJK-TATc7TV3ERvoG855SN0z8",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 1,
            "vicinity": "Nukupure Tapere, Ngatangiia District, Cook Islands, Ngatangiia District"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -21.2461,
                    "lng": -159.824
                },
                "viewport": {
                    "northeast": {
                        "lat": -21.24473812010728,
                        "lng": -159.8225767701073
                    },
                    "southwest": {
                        "lat": -21.24743777989272,
                        "lng": -159.8252764298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Aro'a Beachside Inn",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {

{
    "html_attributions": [],
    "results": [],
    "status": "ZERO_RESULTS"
}
{
    "html_attributions": [],
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 16.297853,
                    "lng": 119.78003
                },
                "viewport": {
                    "northeast": {
                        "lat": 16.29908477989272,
                        "lng": 119.7815971298927
                    },
                    "southwest": {
                        "lat": 16.29638512010727,
                        "lng": 119.7788974701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Hotel G Beach Resort and Restobar",
            "photos": [
                {
                    "height": 3120,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/110271467682865092474\">Kerth Alfonso</a>"
                    ],
                    "photo_reference": "ATtYBwIo3AZ61z_DOVVkFIsP7aM5uOGJZOrk8RcjewUXckGElCxSdLkjF6ZELoLFJkrGk71zS84UUHvPACQWl1jzfozG3nwq9PyFCKh-wJc7x9I8NZeOtn1RsrktxCrWEO9jsv_ZOT_dclJRG2JT6W8HSnegAVGe28NnXHXzHPx17tQ8xWKd",
                    "width": 4160
                }
            ],
            "place_id": "ChIJcbtRhgK4kzMRhF_on7JGSz0",
            "plus_code": {
                "compound_code": "7QXJ+42 Bolinao, Pangasinan, Philippines",
                "global_code": "7P8X7QXJ+42"
            },
            "rating": 5,
            "reference": "ChIJcbtRhgK4kzMRhF_on7JGSz0",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 2,
            "vicinity": "Sitio Abrac, Bolinao"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 16.335323,
                    "lng": 119.7909291
                },
                "viewport": {
                    "northeast": {
                        "lat": 16.33659397989272,
                        "lng": 119.7924138798927
                    },
                    "southwest": {
                        "lat": 16.33389432010728,
                        "lng": 119.7897142201073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Casa Estrella Beach Resort",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3024,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/109394210370249724989\">Edmund Racho</a>"
                    ],
                    "photo_reference": "ATtYBwLRaYCjK8w2kiqGnk3nJhsCHleEaraFE5NPKvaPhE7uhycKHyDeN6nygOJbf3KgRAbaTtvKne9beHJPKGDZ72Wg_aBy6donpxAL-_qZnwlkuUtjUtsm4_BsJhgW8qFSePIRI6l8vz_YazEFjZAwv9gviH_QwjDfWiQXiPc1DCcUAGAK",
                    "width": 4032
                }
            ],
            "place_id": "ChIJb8MubPDJkzMRl3oi8QfcKWE",
            "plus_code": {
                "compound_code": "8QPR+49 Bolinao, Pangasinan, Philippines",
                "global_code": "7P8X8QPR+49"
            },
            "rating": 5,
            "reference": "ChIJb8MubPDJkzMRl3oi8QfcKWE",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 2,
            "vicinity": "Bolinao"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 16.29694,
                    "lng": 119.780121
                },
                "viewport": {
                    "northeast": {
                        "lat": 16.29862827989272,
                        "lng": 119.7816446298927
                    },
                    "southwest": {
                        "lat": 16.29592862010728,
                        "lng": 119.7789449701072
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Treasures of Bolinao Beach Resort and Hotel",
            "photos": [
                {
                    "height": 720,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/118001182672226211977\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwKMsI53RXrgA-r0zc1tDpIkAyDOGXQYtVpJfgoLxFeH0_i1HT-6RmtYZfLNF41uDpwDFbvj4I9Vj-e0dRL70B5drXkl00BNpmKWuPq70ei99KgVfJWrKs09oFXfQM9h5EcKodq7B5tvqYiVhV9npQ9azAjB38zwfnUpOxuKWBM3NIpr",
                    "width": 960
                }
            ],
            "place_id": "ChIJSzkR9QK4kzMR-VIKcmKsgV0",
            "plus_code": {
                "compound_code": "7QWJ+Q2 Bolinao, Pangasinan, Philippines",
                "global_code": "7P8X7QWJ+Q2"
            },
            "rating": 5,
            "reference": "ChIJSzkR9QK4kzMR-VIKcmKsgV0",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 1,
            "vicinity": "Sitio Abrac Patar, Bolinao"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 16.29694,
                    "lng": 119.7801214
                },
                "viewport": {
                    "northeast": {
                        "lat": 16.29862827989272,
                        "lng": 119.7816448298927
                    },
                    "southwest": {
                        "lat": 16.29592862010728,
                        "lng": 119.7789451701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Veue Beach Cabins",
            "opening_hours": {
                "open_now": false
            },
            "photos": [
                {
                    "height": 3264,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/106403516337219660703\">Dustin Andaya</a>"
                    ],
                    "photo_reference": "ATtYBwJWF-WjebpnRBg4kylCGhxkwxwVeYRetYaBYoikhwLzv2qYGsOEWKiJmNIQw_p2SyC_YwIjHtt-19lOVvV9-3kK0iQZ0_k-XWd-wKFDr4Uq8dF9whjtXlZKCTbhju1uSm4lR3JaLmRvUl1Gb2aWofNbsWO2ajq6gnOpUn0M626s1b-4",
                    "width": 4896
                }
            ],
            "place_id": "ChIJW5MdiQK4kzMRsADdDKTsEaI",
            "plus_code": {
                "compound_code": "7QWJ+Q2 Bolinao, Pangasinan, Philippines",
                "global_code": "7P8X7QWJ+Q2"
            },
            "rating": 4.5,
            "reference": "ChIJW5MdiQK4kzMRsADdDKTsEaI",
            "scope": "GOOGLE",
            "types": [
                "real_estate_agency",
                "travel_agency",
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 35,
            "vicinity": "VEUE Beach Cabins Sitio Abrac, Quintos Rd, Bolinao"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 16.3060668,
                    "lng": 119.7810864
                },
                "viewport": {
                    "northeast": {
                        "lat": 16.30719667989272,
                        "lng": 119.7825176298927
                    },
                    "southwest": {
                        "lat": 16.30449702010728,
                        "lng": 119.7798179701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Treasures of Bolinao Beach Resort",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 3456,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/115283681931225028668\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJwmKXK_mWx8DBZq57BVs9fjBeK7GSEsxuQaywp9m5y1S3WaHNBiMNitK12KzpwKwWoeGi7JX9qUIJQNRCwl9eamPJgGtgOP0-tzbbUAEdOjO1zRi0XU1h0DSNy-BNLZ7SK2VzT2_OsK8kUgbSkCtsSNvgNjR4VhPxgjgKz3bS6sz-C",
                    "width": 5184
                }
            ],
            "place_id": "ChIJJX0YX83OkzMR5mtz9fkY924",
            "plus_code": {
                "compound_code": "8Q4J+CC Bolinao, Pangasinan, Philippines",
                "global_code": "7P8X8Q4J+CC"
            },
            "rating": 3.8,
            "reference": "ChIJJX0YX83OkzMR5mtz9fkY924",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 291,
            "vicinity": "Cape Beach Cres, Bolinao"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 16.3345029,
                    "lng": 119.7906049
                },
                "viewport": {
                    "northeast": {
                        "lat": 16.33582712989272,
                        "lng": 119.7919968298927
                    },
                    "southwest": {
                        "lat": 16.33312747010728,
                        "lng": 119.7892971701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Traditional Filipino Villa",
            "photos": [
                {
                    "height": 1908,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/101953039677871482445\">Udo Flagner</a>"
                    ],
                    "photo_reference": "ATtYBwJi1IXP6YUJd7CwYN4RichnmaOvlKbX0k9lHEzXaqUSdcddrPZEjsTQkag9VKuQgsCV8frsoTJ4dBuKsJ59X7HSuZ3j5rwSTYdSTHtUYlc0r862zHAaD0AsneFY-6Qcnb3Y-fTYP1LacfMi4kUk_yxDr-x0r1rO08Kj4e3Ws7harox1",
                    "width": 4032
                }
            ],
            "place_id": "ChIJ6SDoPCrIkzMR8yBggFlYG4g",
            "plus_code": {
                "compound_code": "8QMR+R6 Bolinao, Pangasinan, Philippines",
                "global_code": "7P8X8QMR+R6"
            },
            "rating": 4.3,
            "reference": "ChIJ6SDoPCrIkzMR8yBggFlYG4g",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 11,
            "vicinity": "Bolinao"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 16.2978488,
                    "lng": 119.7800276
                },
                "viewport": {
                    "northeast": {
                        "lat": 16.29908267989272,
                        "lng": 119.7815959298927
                    },
                    "southwest": {
                        "lat": 16.29638302010727,
                        "lng": 119.7788962701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "GResort",
            "photos": [
                {
                    "height": 3000,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/117190326443526334139\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwJzCj3PifYp811hlDuicxrqcc4kU3ckuFZ35MBv3NlDnO3sFd3-dU6O5k42wfurRF0Z6aBNfaHnkIbZgUDr-wUb-B3gFhjW67Z6zDGMrfG44qumjRoIQ5efum3zgCyH8Md1mSyWpQwYtFU7EFl2TydiWH1lUT8swQJmO_QDmXVaK8jA",
                    "width": 4000
                }
            ],
            "place_id": "ChIJqwEnhwK4kzMRNTbWuk1qNzE",
            "plus_code": {
                "compound_code": "7QXJ+42 Bolinao, Pangasinan, Philippines",
                "global_code": "7P8X7QXJ+42"
            },
            "rating": 4.1,
            "reference": "ChIJqwEnhwK4kzMRNTbWuk1qNzE",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 55,
            "vicinity": "Sitio Abrac, Patar, Bolinao"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 16.3026729,
                    "lng": 119.7809888
                },
                "viewport": {
                    "northeast": {
                        "lat": 16.30368717989272,
                        "lng": 119.7824521298927
                    },
                    "southwest": {
                        "lat": 16.30098752010728,
                        "lng": 119.7797524701073
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Patar Beach Resort",
            "photos": [
                {
                    "height": 1860,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/104542087806033291865\">chris abuluyan</a>"
                    ],
                    "photo_reference": "ATtYBwJeru9M5IBd5TCDBxF2diUeIYj9KiAfNQzKwHLkW4gQ54tgd7DpgjSNTKAUDtwYK0_wuyjgu9A6HkamJxzpDDlP_wwCg93C2TYvu3BewmqSmHPIy0R3oztBsqiEl-6RZ6gUmtqMGAyttyXQkROZNzzHr0Uo7AIGYbozhwwYfKYvd8ax",
                    "width": 4032
                }
            ],
            "place_id": "ChIJY64ubvm3kzMRF5yz6OumB2A",
            "plus_code": {
                "compound_code": "8Q3J+39 Bolinao, Pangasinan, Philippines",
                "global_code": "7P8X8Q3J+39"
            },
            "rating": 4.4,
            "reference": "ChIJY64ubvm3kzMRF5yz6OumB2A",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 233,
            "vicinity": "Bolinao"
        }
    ],
    "status": "OK"
}

{
    "html_attributions": [],
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -23.1276524,
                    "lng": -134.9656596
                },
                "viewport": {
                    "northeast": {
                        "lat": -23.12637127010728,
                        "lng": -134.9643498701072
                    },
                    "southwest": {
                        "lat": -23.12907092989272,
                        "lng": -134.9670495298927
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Pension Bianca & Benoit",
            "photos": [
                {
                    "height": 2048,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/115150439809622095143\">Fr\u00e9d\u00e9rick B.</a>"
                    ],
                    "photo_reference": "ATtYBwLS9wsL1qI6HGmO2Yo4NH8z1zAt0EdKLd1hM0h5JWVCe8ziCaG3f7FtlgpTsT0AFEzIiNke7xeXI5YUlpmYlaWfy5T8sp1dqWUaO-nepMI_lKXtBuReD8SdB7NDCrd3k9mC8k_YhL7tuXEFe7if-n6J31TrDo0TE4beSzpeUblKyS7a",
                    "width": 1536
                }
            ],
            "place_id": "ChIJib4T7laIJ54RcJ1rUHQ9KXk",
            "plus_code": {
                "compound_code": "",
                "global_code": "5487V2CM+WP"
            },
            "rating": 4.6,
            "reference": "ChIJib4T7laIJ54RcJ1rUHQ9KXk",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 13,
            "vicinity": "BP 19 | Archipel des Gambier, Mangareva"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -23.1206197,
                    "lng": -134.9687529
                },
                "viewport": {
                    "northeast": {
                        "lat": -23.11945897010728,
                        "lng": -134.9673878201073
                    },
                    "southwest": {
                        "lat": -23.12215862989272,
                        "lng": -134.9700874798928
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Pension Maro'i",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2304,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/111098332724302207930\">popa</a>"
                    ],
                    "photo_reference": "ATtYBwJTgGUOVnMJUSdp1H4iIIN-dnese7dHtMHXmb2wC1diHv3NJU4-L3IJXNoFsRm5K8QNSlq41WRlAGHdP5s4ktXg3eVmn-6PkoFEHInDD_-S73JJD4U-L9MR48NsBHKitX9aJZrhIvGueUnaPKMkrPU8hS3lKDrjJoHGHnNlgqDgD7qI",
                    "width": 4096
                }
            ],
            "place_id": "ChIJnW6Jh0aIJ54RV2HnC1r0Hjw",
            "plus_code": {
                "compound_code": "",
                "global_code": "5487V2HJ+QF"
            },
            "rating": 4,
            "reference": "ChIJnW6Jh0aIJ54RV2HnC1r0Hjw",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 17,
            "vicinity": "Gambier"
        },
        {
            "geometry": {
                "location": {
                    "lat": -23.1096583,
                    "lng": -134.9743477
                },
                "viewport": {
                    "northeast": {
                        "lat": -23.073698,
                        "lng": -134.9292044
                    },
                    "southwest": {
                        "lat": -23.1354104,
                        "lng": -135.0135122
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png",
            "name": "Mangareva",
            "photos": [
                {
                    "height": 1707,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/101672831291437754297\">101672831291437754297</a>"
                    ],
                    "photo_reference": "ATtYBwJPQ966OmMHKGNCNH_oP5H_LO-3YcDmcX2UNrZGIqmFW0WdNWO1lxEhUrqbidCi8bC6eK4vzczw10IPP3wMxbf08tMIvMWQ6M7gtdl0vMKBYtTbDWGJTZ_rOz5SZ3g0aEWXoSbNIVkSf7AJz-hdRQxX5I1tGeW4FJNKK5rlIwOLQfAb",
                    "width": 2560
                }
            ],
            "place_id": "ChIJkRC5RGWIJ54R9kqokhl-dx8",
            "rating": 4.7,
            "reference": "ChIJkRC5RGWIJ54R9kqokhl-dx8",
            "scope": "GOOGLE",
            "types": [
                "natural_feature",
                "establishment"
            ],
            "user_ratings_total": 20,
            "vicinity": "Mangareva, French Polynesia"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": -23.1087258,
                    "lng": -134.9752912
                },
                "viewport": {
                    "northeast": {
                        "lat": -23.10753912010728,
                        "lng": -134.97440245
                    },
                    "southwest": {
                        "lat": -23.11023877989272,
                        "lng": -134.97795745
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/police-71.png",
            "name": "Gendarmerie Nationale",
            "opening_hours": {
                "open_now": false
            },
            "place_id": "ChIJe6TjLUGJJ54RmYDOcAgfYso",
            "plus_code": {
                "compound_code": "",
                "global_code": "5487V2RF+GV"
            },
            "rating": 0,
            "reference": "ChIJe6TjLUGJJ54RmYDOcAgfYso",
            "scope": "GOOGLE",
            "types": [
                "police",
                "local_government_office",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 0,
            "vicinity": "Gambier"
        }
    ],
    "status": "OK"
}

In [ ]:
hotel_df['Hotel Name']= hotel_name
hotel_df = hotel_df.dropna()
hotel_df.to_csv('hotel_export.csv')

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)


# Display figure
fig