# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [18]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [19]:
data_file = "../output_data/output.csv" 

weather_data = pd.read_csv(data_file)
weather_data.drop(columns=["Unnamed: 0"], inplace=True)
weather_data.head()

,City,Country,Date,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed
0,Aksu,CN,1612753668,41.1231,80.2644,33.04,75,11,1.99
1,Bluff,NZ,1612753668,-46.6000,168.3333,59.11,83,100,10.36
2,Guder,ET,1612753668,8.9667,37.7667,53.74,78,70,3.83
3,Qaanaaq,GL,1612753668,77.4840,-69.3632,17.78,85,100,6.98
4,Piaçabuçu,BR,1612753668,-10.4056,-36.4344,78.10,81,99,12.26

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [20]:
gmaps.configure(api_key=g_key)

In [21]:
locations = weather_data[["Latitude", "Longitude"]]

humidity  = weather_data["Humidity"].astype(float)

fig = gmaps.figure()

heatmap_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, point_radius=5)

fig.add_layer(heatmap_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [22]:
vacation_spots = weather_data.loc[weather_data['Max Temperature'] < 85]
vacation_spots = vacation_spots[vacation_spots['Max Temperature'] > 70]
vacation_spots.head()

,City,Country,Date,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed
4,Piaçabuçu,BR,1612753668,-10.4056,-36.4344,78.10,81,99,12.26
17,Kingaroy,AU,1612753670,-26.5333,151.8333,80.60,57,90,9.22
18,Atuona,PF,1612753670,-9.8000,-139.0333,79.56,76,10,19.80
19,Pilar,BR,1612753670,-9.5972,-35.9567,73.40,94,40,4.61
22,Esperance,AU,1612753671,-33.8667,121.9000,82.40,51,15,24.16

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [23]:
def call_places(latitude, longitude, radius, searchType, keyword, key):
    call_string = f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={latitude},{longitude}&radius={radius}&type={searchType}&keyword={keyword}&key={key}"
    return call_string

In [24]:
hotel_df = pd.DataFrame(vacation_spots, columns=["City", "Country", "Lat", "Lng"])

hotel_df["Hotel Name"] = ""
hotel_df

            City Country  Lat  Lng Hotel Name
4      Piaçabuçu      BR  NaN  NaN
17      Kingaroy      AU  NaN  NaN
18        Atuona      PF  NaN  NaN
19         Pilar      BR  NaN  NaN
22     Esperance      AU  NaN  NaN
..           ...     ...  ...  ...        ...
552       Zhuhai      CN  NaN  NaN
557    Morondava      MG  NaN  NaN
566      Mpraeso      GH  NaN  NaN
567  Broken Hill      AU  NaN  NaN
570   Sinazongwe      ZM  NaN  NaN

[161 rows x 5 columns]

In [ ]:
hotel_name = []
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # make request and print url
    name_address = requests.get(call_places(lat,lng,5000,'hotel','hotel',g_key))
    
    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))
    try:
#         hotel_df.iloc[index, 4] = name_address['results'][0]['name']
        hotel_name.append(name_address['results'][0]['name'])
    except IndexError:
        hotel_name.append(np.nan)

In [ ]:
hotel_df['Hotel Name']= hotel_name
hotel_df = hotel_df.dropna()
hotel_df.to_csv('hotel_export.csv')

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)


# Display figure
fig